import prisma from "@/lib/prisma"
import { RECEIPT_METHOD } from "@/types/receipt"
import { resolveSlipDateDisplay } from "@/lib/slip-date"

const LEDGER_METHODS: number[] = [
  RECEIPT_METHOD.DEBIT_NOTE,
  RECEIPT_METHOD.CREDIT_NOTE,
  RECEIPT_METHOD.AGENCY_DEPOSIT,
  RECEIPT_METHOD.AGENCY_WITHDRAW,
  RECEIPT_METHOD.BRANCH_INCOME,
  RECEIPT_METHOD.BRANCH_EXPENSE,
]

export type LedgerReceiptDetail = {
  id: string
  receiptNoString: string
  method: number
  methodName: string
  amount: number
  paymentMethod: number
  paymentMethodName: string
  remarks: string
  bank: string
  cardReference: string
  slipReference: string
  /** YYYY-MM-DD when set */
  slipDate: string | null
  createdAt: Date
  locationId: string | null
  locationName: string | null
  userLocationId: string | null
  agencyId: string | null
  agencyName: string | null
  agencyCode: string | null
  /** For receipt template "Generated By" line */
  createdByName: string | null
  createdById: string | null
}

export async function getLedgerReceiptById(
  id: string
): Promise<{ success: boolean; data?: LedgerReceiptDetail; message?: string }> {
  try {
    const r = await prisma.receipt.findUnique({
      where: { id },
      include: {
        location: { select: { id: true, name: true, addressLine1: true, city: true } },
        userLocation: { select: { id: true, name: true, addressLine1: true, city: true } },
        agency: { select: { id: true, name: true, code: true } },
      },
    })
    if (!r || r.bookingId != null || !LEDGER_METHODS.includes(r.method)) {
      return { success: false, message: "Ledger receipt not found." }
    }
    let createdByName: string | null = null
    let createdById: string | null = null
    if (r.createdBy) {
      const creator = await prisma.user.findUnique({
        where: { id: r.createdBy },
        select: { id: true, name: true },
      })
      createdByName = creator?.name ?? null
      createdById = creator?.id ?? null
    }
    const { RECEIPT_METHOD_NAMES, PAYMENT_METHOD_NAMES } = await import("@/types/receipt")
    const loc = r.location ?? r.userLocation
    const data: LedgerReceiptDetail = {
      id: r.id,
      receiptNoString: r.receiptNoString,
      method: r.method,
      methodName: RECEIPT_METHOD_NAMES[r.method] ?? "—",
      amount: r.amount,
      paymentMethod: r.paymentMethod,
      paymentMethodName: PAYMENT_METHOD_NAMES[r.paymentMethod] ?? "—",
      remarks: r.remarks ?? "",
      bank: r.bank ?? "",
      cardReference: r.cardReference ?? "",
      slipReference: r.slipReference ?? "",
      slipDate: resolveSlipDateDisplay(r.slipDate, r.remarks),
      createdAt: r.createdAt,
      locationId: r.locationId,
      locationName: loc?.name ?? null,
      userLocationId: r.userLocationId,
      agencyId: r.agencyId,
      agencyName: r.agency?.name ?? null,
      agencyCode: r.agency?.code ?? null,
      createdByName,
      createdById,
    }
    return { success: true, data }
  } catch (err) {
    console.error("getLedgerReceiptById error", err)
    return {
      success: false,
      message: err instanceof Error ? err.message : "Failed to load ledger receipt.",
    }
  }
}
