'use client';

import { ColumnDef } from '@tanstack/react-table';
import { Badge } from '@archmage/ui';
import { formatAmount } from '@/lib/utils/currency';
import { formatDateTime } from '@/lib/utils/date';
import {
  BANK_TRANSFER_BATCH_STATUS_LABELS,
  type BankTransferBatchRecord,
  type BankTransferBatchStatus
} from '@/types/payroll';
import RecordActions from './record-actions';

const statusStyles: Record<BankTransferBatchStatus, string> = {
  pending: 'bg-orange-100 text-orange-800 hover:bg-orange-100',
  generated: 'bg-sky-100 text-sky-800 hover:bg-sky-100',
  processed: 'bg-emerald-100 text-emerald-800 hover:bg-emerald-100'
};

export const bankTransferColumns: ColumnDef<BankTransferBatchRecord>[] = [
  {
    id: 'rowNumber',
    header: 'No',
    cell: ({ row, table }) => {
      const pageIndex = table.getState().pagination?.pageIndex ?? 0;
      const pageSize = table.getState().pagination?.pageSize ?? 10;
      return (
        <span className="tabular-nums text-muted-foreground">
          {pageIndex * pageSize + row.index + 1}
        </span>
      );
    },
    enableHiding: false
  },
  {
    accessorKey: 'batchCode',
    header: 'Payroll Batch',
    cell: ({ row }) => (
      <span className="font-medium tabular-nums">
        {row.original.batchCode || '—'}
      </span>
    )
  },
  {
    accessorKey: 'salaryPeriod',
    header: 'Salary Period',
    cell: ({ row }) => (
      <span className="whitespace-nowrap">
        {row.original.salaryPeriod || '—'}
      </span>
    )
  },
  {
    accessorKey: 'staffCount',
    header: 'No. of Staff',
    cell: ({ row }) => (
      <span className="tabular-nums">
        {formatAmount(row.original.staffCount)}
      </span>
    )
  },
  {
    accessorKey: 'totalNetSalary',
    header: 'Total Net Salary',
    cell: ({ row }) => (
      <span className="tabular-nums">
        {formatAmount(row.original.totalNetSalary)}
      </span>
    )
  },
  {
    accessorKey: 'bankName',
    header: 'Bank',
    cell: ({ row }) => (
      <span className="whitespace-nowrap">{row.original.bankName || '—'}</span>
    )
  },
  {
    accessorKey: 'accountCount',
    header: 'Account Count',
    cell: ({ row }) => (
      <span className="tabular-nums">
        {formatAmount(row.original.accountCount)}
      </span>
    )
  },
  {
    accessorKey: 'generatedAt',
    header: 'Generated Date',
    cell: ({ row }) => (
      <span className="whitespace-nowrap tabular-nums">
        {row.original.generatedAt
          ? formatDateTime(row.original.generatedAt, 'dd MMM yyyy')
          : '—'}
      </span>
    )
  },
  {
    accessorKey: 'generatedBy',
    header: 'Generated By',
    cell: ({ row }) => (
      <span className="whitespace-nowrap">
        {row.original.generatedBy || '—'}
      </span>
    )
  },
  {
    accessorKey: 'status',
    header: 'Status',
    cell: ({ row }) => (
      <Badge
        variant="secondary"
        className={statusStyles[row.original.status]}
      >
        {BANK_TRANSFER_BATCH_STATUS_LABELS[row.original.status]}
      </Badge>
    )
  },
  {
    id: 'created',
    header: 'Created',
    cell: ({ row }) => (
      <div className="flex flex-col gap-1">
        <span className="text-xs">{row.original.createdBy || '—'}</span>
        <span className="whitespace-nowrap text-xs text-muted-foreground">
          {row.original.createdAt
            ? formatDateTime(row.original.createdAt)
            : '—'}
        </span>
      </div>
    )
  },
  {
    id: 'updated',
    header: 'Updated',
    cell: ({ row }) => (
      <div className="flex flex-col gap-1">
        <span className="text-xs">{row.original.updatedBy || '—'}</span>
        <span className="whitespace-nowrap text-xs text-muted-foreground">
          {row.original.updatedAt
            ? formatDateTime(row.original.updatedAt)
            : '—'}
        </span>
      </div>
    )
  },
  {
    id: 'actions',
    header: () => <div className="text-right">Actions</div>,
    cell: ({ row }) => <RecordActions record={row.original} />,
    enableHiding: false
  }
];

export const BANK_TRANSFER_EXPORT_COLUMNS = [
  'Payroll Batch',
  'Salary Period',
  'No. of Staff',
  'Total Net Salary',
  'Bank',
  'Account Count',
  'Generated Date',
  'Generated By',
  'Status',
  'Created By',
  'Created At',
  'Updated By',
  'Updated At'
];

export const BANK_TRANSFER_EXPORT_KEYS = [
  'batchCode',
  'salaryPeriod',
  'staffCount',
  'totalNetSalary',
  'bankName',
  'accountCount',
  'generatedAt',
  'generatedBy',
  'status',
  'createdBy',
  'createdAt',
  'updatedBy',
  'updatedAt'
];
