"use client"

import React from "react"
import type { ReceiptTemplateData } from "@/types/receipt-template"

type ReceiptTemplateProps = {
  data: ReceiptTemplateData
  /** Optional class for the root (e.g. for print area) */
  className?: string
}

/**
 * Reusable receipt template component. Renders header (company, location, contact),
 * document title, optional date/time, a configurable table with total row,
 * optional remarks, and footer (Generated By, date).
 * Data is passed in like SMS template variables — same layout, different content.
 */
export function ReceiptTemplate({ data, className }: ReceiptTemplateProps) {
  const { header, title, dateTime, table, remarks, generatedBy, generatedAt } = data
  const hasContact = header.tel || header.email || header.web

  return (
    <div className={className ?? ""}>
      {/* Header */}
      <header className="text-center mb-4">
        <h1 className="text-xl font-bold">{header.companyName}</h1>
        {header.locationName && (
          <p className="text-sm text-muted-foreground mt-0.5">{header.locationName}</p>
        )}
        {hasContact && (
          <p className="text-xs text-muted-foreground mt-1">
            {header.tel && <span>Tel: {header.tel}</span>}
            {(header.email || header.web) && (
              <span>
                {header.tel && " | "}
                {header.email && `Email: ${header.email}`}
                {header.email && header.web && " | "}
                {header.web && `Web: ${header.web}`}
              </span>
            )}
          </p>
        )}
      </header>

      {/* Document title */}
      <h2 className="text-lg font-semibold text-center mb-4">{title}</h2>

      {/* Optional date/time */}
      {dateTime != null && dateTime !== "" && (
        <p className="text-sm mb-3">
          <span className="font-medium">Date/Time :</span> {dateTime}
        </p>
      )}

      {/* Table */}
      <div className="border rounded-md overflow-hidden mb-4">
        <table className="w-full text-sm border-collapse">
          <thead>
            <tr className="bg-muted/50">
              {table.columns.map((col) => (
                <th key={col.key} className="border border-border px-3 py-2 text-left font-semibold">
                  {col.label}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {table.rows.map((row, rowIndex) => (
              <tr key={rowIndex} className="border-b border-border">
                {table.columns.map((col) => (
                  <td key={col.key} className="border border-border px-3 py-2">
                    {row[col.key] ?? "—"}
                  </td>
                ))}
              </tr>
            ))}
            {table.totalLabel != null && table.totalAmountKey != null && (
              <tr className="bg-muted/30 font-medium">
                {table.columns.map((col) => {
                  const isTotalAmount = col.key === table.totalAmountKey
                  const isTotalLabel =
                    col.key === (table.totalLabelColumnKey ?? table.columns[1]?.key)
                  return (
                    <td key={col.key} className="border border-border px-3 py-2">
                      {isTotalAmount
                        ? table.rows
                            .reduce(
                              (sum, r) =>
                                sum +
                                (parseFloat(String(r[table.totalAmountKey!]).replace(/,/g, "")) || 0),
                              0
                            )
                            .toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })
                        : isTotalLabel
                          ? table.totalLabel
                          : ""}
                    </td>
                  )
                })}
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* Remarks */}
      {remarks != null && remarks !== "" && (
        <p className="text-sm mb-2">
          <span className="font-medium">Remarks :</span> {remarks}
        </p>
      )}

      {/* Footer */}
      <footer className="text-sm text-muted-foreground mt-4 pt-2 border-t border-border flex flex-wrap justify-between gap-2">
        {generatedBy != null && generatedBy !== "" && (
          <span>
            <span className="font-medium">Generated By :</span> {generatedBy}
          </span>
        )}
        {generatedAt != null && generatedAt !== "" && <span>{generatedAt}</span>}
      </footer>
    </div>
  )
}
