'use client';

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { DateTimeRangePicker } from '@/components/common/date-time-range-picker';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/components/hooks/use-toast';
import { Download, FileSpreadsheet, FileText, Loader2, Printer, SearchIcon, X } from 'lucide-react';
import { getAllCashierSummaryDetailReportData } from '@/app/actions/reports/all-cashier-summary-detail.action';
import { formatReceiptAmount } from '@/lib/format-money';
import { formatReportRangeLabel } from '@/lib/format-report-range-label';
import { formatExportFileName } from '@/lib/utils';
import { ReportUserSelect } from '@/components/common/user-select';
import { ReportGenerationDetailsCard } from '@/components/common/report-generation-details';
import {
  ReportPrintLayout,
  downloadBrandedReportExcel,
  downloadBrandedReportPdf,
  toBrandedPdfSummaryItems,
} from '@/components/common/report-print';
import type { ReportPrintSummaryItem } from '@/components/common/report-print';
import type {
  AllCashierUserDetailRow,
  AllCashierUserSummaryRow,
  CashierSummaryPaymentAmounts,
} from '@/types/report';

type Props = {
  initialUserOptions: Array<{ id: string; name: string }>;
  initialLocationOptions: Array<{ id: string; name: string }>;
  currentUserName: string;
};

const PAYMENT_COLUMNS: { key: keyof CashierSummaryPaymentAmounts; label: string }[] = [
  { key: 'cash', label: 'Cash' },
  { key: 'creditCard', label: 'Credit Card' },
  { key: 'slip', label: 'Slip' },
  { key: 'cheque', label: 'Cheque' },
  { key: 'agent', label: 'Agent' },
  { key: 'agentCredit', label: 'Credit' },
  { key: 'eWallet', label: 'E-wallet' },
];

function formatAmount(n: number | undefined | null): string {
  const num = Number(n);
  if (!Number.isFinite(num)) return '0.00';
  return formatReceiptAmount(num);
}

function formatAmountForCsv(n: number | undefined | null): string {
  const num = Number(n);
  if (!Number.isFinite(num)) return '0.00';
  // Receipt.amount is already in rupees (not cents), so do not divide by 100.
  return num.toFixed(2);
}

function getDefaultDateTimeRange(): { from: string; to: string } {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  return { from: `${y}-${m}-${d}T00:00`, to: `${y}-${m}-${d}T23:59` };
}

export default function AllCashierSummaryDetailContent({
  initialUserOptions,
  initialLocationOptions,
  currentUserName,
}: Props) {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [fromDateTime, setFromDateTime] = useState<string>(() => getDefaultDateTimeRange().from);
  const [toDateTime, setToDateTime] = useState<string>(() => getDefaultDateTimeRange().to);
  const [userId, setUserId] = useState<string>('__all__');
  const [locationId, setLocationId] = useState<string>('__all__');
  const [format, setFormat] = useState<'summary' | 'detail'>('summary');
  const [summaryRows, setSummaryRows] = useState<AllCashierUserSummaryRow[]>([]);
  const [detailRows, setDetailRows] = useState<AllCashierUserDetailRow[]>([]);
  const [grandTotals, setGrandTotals] = useState<CashierSummaryPaymentAmounts | null>(null);
  const [totalReceipts, setTotalReceipts] = useState(0);
  const [loadingExcel, setLoadingExcel] = useState(false);
  const [reportMeta, setReportMeta] = useState<{
    from: string;
    to: string;
    userLabel: string;
    locationLabel: string;
    format: 'summary' | 'detail';
    generatedAt: string;
    generatedBy: string;
  } | null>(null);

  const userOptions = initialUserOptions;

  const buildSummaryItems = (meta: {
    from: string;
    to: string;
    userLabel: string;
    locationLabel: string;
    format: 'summary' | 'detail';
    generatedAt: string;
    generatedBy: string;
  }): ReportPrintSummaryItem[] => [
    { label: 'Period', value: formatReportRangeLabel(meta.from, meta.to) },
    { label: 'Staff', value: meta.userLabel },
    { label: 'Branch', value: meta.locationLabel },
    { label: 'Report Type', value: meta.format === 'detail' ? 'Detail' : 'Summary' },
    { label: 'Generated By', value: meta.generatedBy },
    { label: 'Generated At', value: meta.generatedAt },
  ];

  const renderReportMetaCard = (meta: {
    from: string;
    to: string;
    userLabel: string;
    locationLabel: string;
    format: 'summary' | 'detail';
    generatedAt: string;
    generatedBy: string;
  }) => (
    <ReportGenerationDetailsCard
      items={[
        {
          label: 'Filters',
          value: (
            <>
              User: {meta.userLabel} | Branch: {meta.locationLabel} | Range:{' '}
              {formatReportRangeLabel(meta.from, meta.to)} | Format:{' '}
              {meta.format === 'detail' ? 'Detail' : 'Summary'}
            </>
          ),
          smColSpan: 2,
        },
        { label: 'Generated by', value: <span className="font-semibold">{meta.generatedBy}</span> },
        { label: 'Generated at', value: <span className="font-semibold">{meta.generatedAt}</span> },
      ]}
    />
  );

  const runSearch = async () => {
    if (!fromDateTime || !toDateTime) {
      toast({ variant: 'destructive', title: 'Validation Error', description: 'Please select from/to date & time' });
      return;
    }
    setLoading(true);
    try {
      const res = await getAllCashierSummaryDetailReportData({
        userId,
        locationId,
        dateFrom: fromDateTime,
        dateTo: toDateTime,
        format,
      });
      if (!res.success) {
        toast({ variant: 'destructive', title: 'Error', description: res.message || 'Failed to load report' });
        setSummaryRows([]);
        setDetailRows([]);
        setGrandTotals(null);
        setTotalReceipts(0);
        setReportMeta(null);
        return;
      }
      setSummaryRows(res.summaryRows);
      setDetailRows(res.detailRows);
      setGrandTotals(res.grandTotals);
      setTotalReceipts(res.totalReceipts);
      setReportMeta({
        from: fromDateTime,
        to: toDateTime,
        userLabel: userOptions.find((u) => u.id === userId)?.name ?? 'All Users',
        locationLabel: initialLocationOptions.find((l) => l.id === locationId)?.name ?? 'All Branches',
        format,
        generatedAt: new Date().toLocaleString(),
        generatedBy: currentUserName,
      });
    } catch (error: unknown) {
      const msg = error instanceof Error ? error.message : 'Failed to load report';
      toast({ variant: 'destructive', title: 'Error', description: msg });
    } finally {
      setLoading(false);
    }
  };

  const downloadCsv = () => {
    const lines: string[] = [];
    if (format === 'summary') {
      lines.push(['User', 'Receipt Count', ...PAYMENT_COLUMNS.map((c) => c.label)].join(','));
      for (const r of summaryRows) {
        lines.push(
          [
            r.userName,
            String(r.receiptCount),
            ...PAYMENT_COLUMNS.map((c) => formatAmountForCsv(r[c.key])),
          ]
            .map((x) => `"${String(x).replace(/"/g, '""')}"`)
            .join(',')
        );
      }
    } else {
      lines.push(['User', 'Section', 'Receipt Count', ...PAYMENT_COLUMNS.map((c) => c.label)].join(','));
      for (const u of detailRows) {
        for (const s of u.sections) {
          lines.push(
            [
              u.userName,
              s.title,
              String(s.receiptCount),
              ...PAYMENT_COLUMNS.map((c) => formatAmountForCsv(s.totals[c.key])),
            ]
              .map((x) => `"${String(x).replace(/"/g, '""')}"`)
              .join(',')
          );
        }
      }
    }
    const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `all-cashier-summary-detail-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadExcel = async () => {
    const hasRows =
      format === 'summary' ? summaryRows.length > 0 : detailRows.length > 0;
    if ((!hasRows && !grandTotals) || !reportMeta) {
      toast({ variant: 'destructive', title: 'No data', description: 'Run a search first to download Excel.' });
      return;
    }

    setLoadingExcel(true);
    try {
      const fileName = `${formatExportFileName('all-cashier-summary-detail')}.xlsx`;
      const reportName = 'All Cashier Summary and Detail Report';
      const summaryItems = toBrandedPdfSummaryItems(buildSummaryItems(reportMeta));

      if (format === 'summary') {
        type ExcelRow = {
          no: string | null;
          userName: string;
          receiptCount: string;
          cash: string;
          creditCard: string;
          slip: string;
          cheque: string;
          agent: string;
          agentCredit: string;
          eWallet: string;
          handoverDate: string | null;
          checkedBy: string | null;
        };
        const data: ExcelRow[] = summaryRows.map((r, i) => ({
          no: String(i + 1),
          userName: r.userName,
          receiptCount: String(r.receiptCount),
          cash: formatAmountForCsv(r.cash),
          creditCard: formatAmountForCsv(r.creditCard),
          slip: formatAmountForCsv(r.slip),
          cheque: formatAmountForCsv(r.cheque),
          agent: formatAmountForCsv(r.agent),
          agentCredit: formatAmountForCsv(r.agentCredit),
          eWallet: formatAmountForCsv(r.eWallet),
          handoverDate: null,
          checkedBy: null,
        }));
        if (grandTotals) {
          data.push({
            no: null,
            userName: 'Total',
            receiptCount: String(totalReceipts),
            cash: formatAmountForCsv(grandTotals.cash),
            creditCard: formatAmountForCsv(grandTotals.creditCard),
            slip: formatAmountForCsv(grandTotals.slip),
            cheque: formatAmountForCsv(grandTotals.cheque),
            agent: formatAmountForCsv(grandTotals.agent),
            agentCredit: formatAmountForCsv(grandTotals.agentCredit),
            eWallet: formatAmountForCsv(grandTotals.eWallet),
            handoverDate: null,
            checkedBy: null,
          });
        }
        await downloadBrandedReportExcel({
          reportName,
          summaryItems,
          generatedAt: reportMeta.generatedAt,
          data,
          columns: [
            'No.',
            'User',
            'Receipts',
            ...PAYMENT_COLUMNS.map((c) => c.label),
            'Handover Date',
            'Checked By',
          ],
          keys: [
            'no',
            'userName',
            'receiptCount',
            'cash',
            'creditCard',
            'slip',
            'cheque',
            'agent',
            'agentCredit',
            'eWallet',
            'handoverDate',
            'checkedBy',
          ],
          fileName,
          sheetName: 'All Cashier Summary',
          orientation: 'portrait',
        });
        return;
      }

      type DetailExcelRow = {
        userName: string;
        section: string;
        receiptCount: string;
        cash: string;
        creditCard: string;
        slip: string;
        cheque: string;
        agent: string;
        agentCredit: string;
        eWallet: string;
      };
      const data: DetailExcelRow[] = [];
      for (const u of detailRows) {
        for (const s of u.sections) {
          data.push({
            userName: u.userName,
            section: s.title,
            receiptCount: String(s.receiptCount),
            cash: formatAmountForCsv(s.totals.cash),
            creditCard: formatAmountForCsv(s.totals.creditCard),
            slip: formatAmountForCsv(s.totals.slip),
            cheque: formatAmountForCsv(s.totals.cheque),
            agent: formatAmountForCsv(s.totals.agent),
            agentCredit: formatAmountForCsv(s.totals.agentCredit),
            eWallet: formatAmountForCsv(s.totals.eWallet),
          });
        }
        data.push({
          userName: u.userName,
          section: 'User Total',
          receiptCount: String(u.receiptCount),
          cash: formatAmountForCsv(u.totals.cash),
          creditCard: formatAmountForCsv(u.totals.creditCard),
          slip: formatAmountForCsv(u.totals.slip),
          cheque: formatAmountForCsv(u.totals.cheque),
          agent: formatAmountForCsv(u.totals.agent),
          agentCredit: formatAmountForCsv(u.totals.agentCredit),
          eWallet: formatAmountForCsv(u.totals.eWallet),
        });
      }
      if (grandTotals) {
        data.push({
          userName: 'Grand Total',
          section: '',
          receiptCount: String(totalReceipts),
          cash: formatAmountForCsv(grandTotals.cash),
          creditCard: formatAmountForCsv(grandTotals.creditCard),
          slip: formatAmountForCsv(grandTotals.slip),
          cheque: formatAmountForCsv(grandTotals.cheque),
          agent: formatAmountForCsv(grandTotals.agent),
          agentCredit: formatAmountForCsv(grandTotals.agentCredit),
          eWallet: formatAmountForCsv(grandTotals.eWallet),
        });
      }
      await downloadBrandedReportExcel({
        reportName,
        summaryItems,
        generatedAt: reportMeta.generatedAt,
        data,
        columns: ['User', 'Section', 'Receipts', ...PAYMENT_COLUMNS.map((c) => c.label)],
        keys: [
          'userName',
          'section',
          'receiptCount',
          'cash',
          'creditCard',
          'slip',
          'cheque',
          'agent',
          'agentCredit',
          'eWallet',
        ],
        fileName,
        sheetName: 'All Cashier Detail',
        orientation: 'portrait',
      });
    } catch (error: unknown) {
      toast({
        variant: 'destructive',
        title: 'Excel export failed',
        description: error instanceof Error ? error.message : 'Unable to generate Excel.',
      });
    } finally {
      setLoadingExcel(false);
    }
  };

  const downloadPdf = async () => {
    const hasRows =
      format === 'summary' ? summaryRows.length > 0 : detailRows.length > 0;
    if (!hasRows && !grandTotals) {
      toast({ variant: 'destructive', title: 'No data', description: 'Run a search first to download PDF.' });
      return;
    }
    if (!reportMeta) {
      toast({ variant: 'destructive', title: 'No data', description: 'Run a search first to download PDF.' });
      return;
    }

    const summaryItems = toBrandedPdfSummaryItems(buildSummaryItems(reportMeta));
    const fileName = `${formatExportFileName('all-cashier-summary-detail')}.pdf`;

    if (format === 'summary') {
      type PdfRow = {
        no: string;
        userName: string;
        receiptCount: string;
        cash: string;
        creditCard: string;
        slip: string;
        cheque: string;
        agent: string;
        agentCredit: string;
        eWallet: string;
        handoverDate: string;
        checkedBy: string;
      };
      const data: PdfRow[] = summaryRows.map((r, i) => ({
        no: String(i + 1),
        userName: r.userName,
        receiptCount: String(r.receiptCount),
        cash: formatAmountForCsv(r.cash),
        creditCard: formatAmountForCsv(r.creditCard),
        slip: formatAmountForCsv(r.slip),
        cheque: formatAmountForCsv(r.cheque),
        agent: formatAmountForCsv(r.agent),
        agentCredit: formatAmountForCsv(r.agentCredit),
        eWallet: formatAmountForCsv(r.eWallet),
        handoverDate: '----------',
        checkedBy: '----------',
      }));
      if (grandTotals) {
        data.push({
          no: '',
          userName: 'Total',
          receiptCount: String(totalReceipts),
          cash: formatAmountForCsv(grandTotals.cash),
          creditCard: formatAmountForCsv(grandTotals.creditCard),
          slip: formatAmountForCsv(grandTotals.slip),
          cheque: formatAmountForCsv(grandTotals.cheque),
          agent: formatAmountForCsv(grandTotals.agent),
          agentCredit: formatAmountForCsv(grandTotals.agentCredit),
          eWallet: formatAmountForCsv(grandTotals.eWallet),
          handoverDate: '',
          checkedBy: '',
        });
      }
      await downloadBrandedReportPdf({
        reportName: 'All Cashier Summary and Detail Report',
        summaryItems,
        generatedAt: reportMeta.generatedAt,
        data,
        columns: [
          'No.',
          'User',
          'Receipts',
          ...PAYMENT_COLUMNS.map((c) => c.label),
          'Handover Date',
          'Checked By',
        ],
        keys: [
          'no',
          'userName',
          'receiptCount',
          'cash',
          'creditCard',
          'slip',
          'cheque',
          'agent',
          'agentCredit',
          'eWallet',
          'handoverDate',
          'checkedBy',
        ],
        fileName,
        orientation: 'portrait',
      });
      return;
    }
    type DetailPdfRow = {
      userName: string;
      section: string;
      receiptCount: string;
      cash: string;
      creditCard: string;
      slip: string;
      cheque: string;
      agent: string;
      agentCredit: string;
      eWallet: string;
    };
    const data: DetailPdfRow[] = [];
    for (const u of detailRows) {
      for (const s of u.sections) {
        data.push({
          userName: u.userName,
          section: s.title,
          receiptCount: String(s.receiptCount),
          cash: formatAmountForCsv(s.totals.cash),
          creditCard: formatAmountForCsv(s.totals.creditCard),
          slip: formatAmountForCsv(s.totals.slip),
          cheque: formatAmountForCsv(s.totals.cheque),
          agent: formatAmountForCsv(s.totals.agent),
          agentCredit: formatAmountForCsv(s.totals.agentCredit),
          eWallet: formatAmountForCsv(s.totals.eWallet),
        });
      }
      data.push({
        userName: u.userName,
        section: 'User Total',
        receiptCount: String(u.receiptCount),
        cash: formatAmountForCsv(u.totals.cash),
        creditCard: formatAmountForCsv(u.totals.creditCard),
        slip: formatAmountForCsv(u.totals.slip),
        cheque: formatAmountForCsv(u.totals.cheque),
        agent: formatAmountForCsv(u.totals.agent),
        agentCredit: formatAmountForCsv(u.totals.agentCredit),
        eWallet: formatAmountForCsv(u.totals.eWallet),
      });
    }
    if (grandTotals) {
      data.push({
        userName: 'Grand Total',
        section: '',
        receiptCount: String(totalReceipts),
        cash: formatAmountForCsv(grandTotals.cash),
        creditCard: formatAmountForCsv(grandTotals.creditCard),
        slip: formatAmountForCsv(grandTotals.slip),
        cheque: formatAmountForCsv(grandTotals.cheque),
        agent: formatAmountForCsv(grandTotals.agent),
        agentCredit: formatAmountForCsv(grandTotals.agentCredit),
        eWallet: formatAmountForCsv(grandTotals.eWallet),
      });
    }
    await downloadBrandedReportPdf({
      reportName: 'All Cashier Summary and Detail Report',
      summaryItems,
      generatedAt: reportMeta.generatedAt,
      data,
      columns: ['User', 'Section', 'Receipts', ...PAYMENT_COLUMNS.map((c) => c.label)],
      keys: [
        'userName',
        'section',
        'receiptCount',
        'cash',
        'creditCard',
        'slip',
        'cheque',
        'agent',
        'agentCredit',
        'eWallet',
      ],
      fileName,
      orientation: 'portrait',
    });
  };

  return (
    <div className="w-full py-2 space-y-3">
      <style>{`
        @media print {
          body {
            background: #fff !important;
            color: #000 !important;
            margin: 0 !important;
            padding: 0 !important;
          }
          .all-cashier-print-report {
            border: 0 !important;
            padding: 0 !important;
            margin: 0 !important;
            background: #fff !important;
            box-shadow: none !important;
          }
          .all-cashier-print-report > div {
            padding: 0 !important;
          }
          .all-cashier-print-report .overflow-x-auto,
          .all-cashier-print-report .overflow-auto {
            overflow: visible !important;
          }
          .all-cashier-print-report [class*="border-dotted"] {
            border-bottom: 1px dotted #000 !important;
            min-height: 14px !important;
          }
          /* Portrait: keep all summary columns readable on narrower page */
          .all-cashier-print-report .rpt-print-root table {
            table-layout: fixed !important;
            width: 100% !important;
          }
          .all-cashier-print-report .rpt-print-root th,
          .all-cashier-print-report .rpt-print-root td {
            font-size: 6.5pt !important;
            padding: 0.8mm 0.6mm !important;
            line-height: 1.15 !important;
          }
          .all-cashier-print-report .rpt-print-root thead th,
          .all-cashier-print-report .rpt-print-root th {
            font-size: 6pt !important;
          }
          .all-cashier-print-report .rpt-print-root [class*="w-[130px]"] {
            width: 100% !important;
            max-width: none !important;
          }
        }
      `}</style>
      <Card className="print:hidden">
        <CardHeader className="pb-2">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
            <div>
              <CardTitle className="text-xl font-bold">All Cashier Summary and Detail Report</CardTitle>
              <CardDescription className="text-xs mt-0.5">
                Summary aggregates receipts by cashier. Detail shows section-wise totals per cashier.
              </CardDescription>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={() => window.print()} className="gap-2"><Printer />Print</Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => {
                  void downloadPdf().catch((error: unknown) => {
                    toast({
                      variant: 'destructive',
                      title: 'PDF export failed',
                      description:
                        error instanceof Error ? error.message : 'Unable to generate PDF.',
                    });
                  });
                }}
                className="gap-2"
              >
                <FileText />
                PDF
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => {
                  void downloadExcel();
                }}
                disabled={loadingExcel}
                className="gap-2"
              >
                {loadingExcel ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <FileSpreadsheet className="h-4 w-4" />
                )}
                Excel
              </Button>
              <Button variant="outline" size="sm" onClick={downloadCsv} className="gap-2">
                <Download />
                Download CSV
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-wrap items-end gap-4">
            <DateTimeRangePicker
              label="Date & time range"
              from={fromDateTime}
              to={toDateTime}
              onChange={({ from, to }) => {
                setFromDateTime(from ?? '');
                setToDateTime(to ?? '');
              }}
            />
            <div>
              <label className="text-sm font-semibold mb-2 block">Branch</label>
              <div className="flex items-center gap-1">
                <Select value={locationId} onValueChange={setLocationId}>
                  <SelectTrigger className="w-[200px]"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {initialLocationOptions.map((opt) => (
                      <SelectItem key={opt.id} value={opt.id}>{opt.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {locationId !== '__all__' ? (
                  <Button
                    type="button"
                    variant="outline"
                    size="icon"
                    className="h-9 w-9 shrink-0"
                    aria-label="Clear branch"
                    onClick={() => setLocationId('__all__')}
                  >
                    <X className="h-4 w-4" />
                  </Button>
                ) : null}
              </div>
            </div>
            <ReportUserSelect
              userOptions={userOptions}
              value={userId}
              onChange={setUserId}
              label="Select User"
              widthClassName="w-[200px]"
            />
            <div>
              <label className="text-sm font-semibold mb-2 block">Format</label>
              <Select value={format} onValueChange={(v) => setFormat(v as 'summary' | 'detail')}>
                <SelectTrigger className="w-[140px]"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="summary">Summary</SelectItem>
                  <SelectItem value="detail">Detail</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button size="sm" onClick={runSearch} disabled={loading} className="h-10 gap-2">
              <SearchIcon className="h-4 w-4" />Search
            </Button>
          </div>
        </CardContent>
      </Card>

      {!reportMeta && (
        <Card className="border-dashed print:hidden">
          <CardContent className="py-8">
            <p className="text-sm font-medium text-muted-foreground">Search to view report details.</p>
          </CardContent>
        </Card>
      )}

      {reportMeta && (
        <Card className="all-cashier-print-report bg-muted/20 print:shadow-none print:border-0 print:bg-white">
          <CardHeader className="py-2 print:hidden">
            <CardTitle className="text-base">All Cashier Summary and Detail Report</CardTitle>
            <CardDescription className="text-xs mt-0.5">
              All-cashier report with summary/detail modes for the selected filters.
            </CardDescription>
            {renderReportMetaCard(reportMeta)}
          </CardHeader>
          <CardContent className="space-y-3 py-2">
            <ReportPrintLayout
              reportName="All Cashier Summary and Detail Report"
              pageSize="A4 portrait"
              generatedAt={reportMeta.generatedAt}
              summaryItems={buildSummaryItems(reportMeta)}
            >
              {loading ? (
                <div className="text-center py-8">Loading...</div>
              ) : format === 'summary' ? (
                <div className="rounded-md border overflow-x-auto">
                  <Table className="text-[11px] [&_th]:px-1.5 [&_td]:px-1.5 [&_th]:border-r [&_th:last-child]:border-r-0 [&_td]:border-r [&_td:last-child]:border-r-0">
                    <TableHeader>
                      <TableRow className="border-b">
                        <TableHead className="w-10 text-right">No.</TableHead>
                        <TableHead className="pr-0">User</TableHead>
                        <TableHead className="text-right">Receipts</TableHead>
                        {PAYMENT_COLUMNS.map((c) => (
                          <TableHead key={c.key} className="text-right tabular-nums">{c.label}</TableHead>
                        ))}
                        <TableHead className="text-center">Handover Date</TableHead>
                        <TableHead className="text-center">Checked By</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {summaryRows.map((r, i) => (
                        <TableRow key={r.userId} className="border-b border-border/50">
                          <TableCell className="text-center tabular-nums">{i + 1}</TableCell>
                          <TableCell className="pr-0">{r.userName}</TableCell>
                          <TableCell className="text-right tabular-nums">{r.receiptCount}</TableCell>
                          {PAYMENT_COLUMNS.map((c) => (
                            <TableCell key={c.key} className="text-right tabular-nums">{formatAmount(r[c.key])}</TableCell>
                          ))}
                          <TableCell className="text-center">
                            <div
                              className="min-h-10 border-b-2 border-dotted border-foreground/45 mx-auto block w-[130px]"
                              aria-hidden
                            />
                          </TableCell>
                          <TableCell className="text-center">
                            <div
                              className="min-h-10 border-b-2 border-dotted border-foreground/45 mx-auto block w-[130px]"
                              aria-hidden
                            />
                          </TableCell>
                        </TableRow>
                      ))}
                      {grandTotals && (
                        <TableRow className="rpt-print-total font-medium bg-muted/50">
                          <TableCell colSpan={3} className="text-left">Total</TableCell>
                          {PAYMENT_COLUMNS.map((c) => (
                            <TableCell key={c.key} className="text-right tabular-nums">{formatAmount(grandTotals[c.key])}</TableCell>
                          ))}
                          <TableCell />
                          <TableCell />
                        </TableRow>
                      )}
                    </TableBody>
                  </Table>
                </div>
              ) : (
                <div className="space-y-3">
                  {detailRows.map((u, idx) => (
                    <div key={u.userId} className="rounded-md border overflow-x-auto">
                      <Table className="text-[11px] [&_th]:px-1.5 [&_td]:px-1.5 [&_th]:border-r [&_td]:border-r">
                        <TableHeader>
                          <TableRow className="border-b">
                            <TableHead className="w-10 text-right">No.</TableHead>
                            <TableHead className="pr-0">User</TableHead>
                            <TableHead>Section</TableHead>
                            <TableHead className="text-right">Receipts</TableHead>
                            {PAYMENT_COLUMNS.map((c) => (
                              <TableHead key={c.key} className="text-right tabular-nums">{c.label}</TableHead>
                            ))}
                            <TableHead className="text-center">Handover Date</TableHead>
                            <TableHead className="text-center">Checked By</TableHead>
                          </TableRow>
                        </TableHeader>
                        <TableBody>
                          {u.sections.map((s, i) => (
                            <TableRow key={`${u.userId}-${s.key}`} className="border-b border-border/50">
                              <TableCell className="text-center tabular-nums">{i === 0 ? idx + 1 : ''}</TableCell>
                              <TableCell className="pr-0">{i === 0 ? u.userName : ''}</TableCell>
                              <TableCell>{s.title}</TableCell>
                              <TableCell className="text-right tabular-nums">{s.receiptCount}</TableCell>
                              {PAYMENT_COLUMNS.map((c) => (
                                <TableCell key={c.key} className="text-right tabular-nums">{formatAmount(s.totals[c.key])}</TableCell>
                              ))}
                              {i === 0 && (
                                <>
                                  <TableCell
                                    rowSpan={u.sections.length + 1}
                                    className="text-center"
                                  >
                                    <div
                                      className="min-h-10 border-b-2 border-dotted border-foreground/45 mx-auto block w-[130px]"
                                      aria-hidden
                                    />
                                  </TableCell>
                                  <TableCell
                                    rowSpan={u.sections.length + 1}
                                    className="text-center"
                                  >
                                    <div
                                      className="min-h-10 border-b-2 border-dotted border-foreground/45 mx-auto block w-[130px]"
                                      aria-hidden
                                    />
                                  </TableCell>
                                </>
                              )}
                            </TableRow>
                          ))}
                          <TableRow className="rpt-print-total font-medium bg-muted/50">
                            <TableCell colSpan={3}>User Total</TableCell>
                            <TableCell className="text-right tabular-nums">{u.receiptCount}</TableCell>
                            {PAYMENT_COLUMNS.map((c) => (
                              <TableCell key={c.key} className="text-right tabular-nums">{formatAmount(u.totals[c.key])}</TableCell>
                            ))}
                          </TableRow>
                        </TableBody>
                      </Table>
                    </div>
                  ))}
                  {grandTotals && (
                    <div className="rounded-md border overflow-x-auto">
                      <Table className="text-[11px] [&_th]:px-1.5 [&_td]:px-1.5 [&_th]:border-r [&_th:last-child]:border-r-0 [&_td]:border-r [&_td:last-child]:border-r-0">
                        <TableHeader>
                          <TableRow className="border-b">
                            <TableHead colSpan={4}>Grand Total</TableHead>
                            {PAYMENT_COLUMNS.map((c) => (
                              <TableHead key={c.key} className="text-right tabular-nums">{c.label}</TableHead>
                            ))}
                            <TableHead />
                            <TableHead />
                          </TableRow>
                        </TableHeader>
                        <TableBody>
                          <TableRow className="rpt-print-total font-medium bg-muted/50">
                            <TableCell colSpan={4}>Total</TableCell>
                            {PAYMENT_COLUMNS.map((c) => (
                              <TableCell key={c.key} className="text-right tabular-nums">{formatAmount(grandTotals[c.key])}</TableCell>
                            ))}
                            <TableCell />
                            <TableCell />
                          </TableRow>
                        </TableBody>
                      </Table>
                    </div>
                  )}
                  <div className="rounded-md border border-primary/20 bg-primary/[0.03] px-3 py-2 text-[11px] print:hidden">
                    <span className="text-muted-foreground">Total receipts in report:</span> <span className="font-semibold">{totalReceipts}</span>
                  </div>
                  <div className="print:hidden">{renderReportMetaCard(reportMeta)}</div>
                </div>
              )}
            </ReportPrintLayout>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
