'use client';

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Selector } from '@/components/common/selector';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/components/hooks/use-toast';
import { Download, Printer, SearchIcon } from 'lucide-react';
import { getAgentBalanceReportData } from '@/app/actions/reports/agent-balance.report.action';
import type { AgentBalanceReportContentProps, AgentBalanceReportRow } from '@/types/reports/agent-balance';
import { formatLKR } from '@/lib/format-money';
import { ReportAgentSelect } from '@/components/common/agent-select';
import { ReportGenerationDetailsCard } from '@/components/common/report-generation-details';
import { ReportEmptyStateCard } from '@/components/common/report-empty-state';

const STATUS_OPTIONS = [
  { id: '1', name: 'Active' },
  { id: '0', name: 'Inactive' },
];

export default function AgentBalanceReportContent({ agentOptions, currentUserName }: AgentBalanceReportContentProps) {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [agentId, setAgentId] = useState('__all__');
  const [status, setStatus] = useState('__all__');
  const [rows, setRows] = useState<AgentBalanceReportRow[]>([]);
  const [reportMeta, setReportMeta] = useState<{
    agentLabel: string;
    statusLabel: string;
    generatedBy: string;
    generatedAt: string;
  } | null>(null);

  const balanceTotal = rows.reduce((sum, r) => sum + (Number(r.agentBalance) || 0), 0);

  const runSearch = async () => {
    setLoading(true);
    try {
      const res = await getAgentBalanceReportData({ agentId, status });
      if (!res.success) {
        toast({ variant: 'destructive', title: 'Error', description: res.message || 'Failed to load report' });
        setRows([]);
        setReportMeta(null);
        return;
      }
      const data = res.data ?? [];
      setRows(data);
      setReportMeta({
        agentLabel: agentOptions.find((a) => a.id === agentId)?.name ?? 'All Agents',
        statusLabel: STATUS_OPTIONS.find((s) => s.id === status)?.name ?? 'All Status',
        generatedBy: currentUserName,
        generatedAt: new Date().toLocaleString(),
      });
    } catch (error: unknown) {
      const msg = error instanceof Error ? error.message : 'Failed to load report';
      toast({ variant: 'destructive', title: 'Error', description: msg });
    } finally {
      setLoading(false);
    }
  };

  const renderMetaCard = () =>
    reportMeta ? (
      <ReportGenerationDetailsCard
        items={[
          {
            label: 'Filters',
            value: (
              <>
                Agent: {reportMeta.agentLabel} | Status: {reportMeta.statusLabel}
              </>
            ),
            smColSpan: 2,
          },
          { label: 'Generated by', value: <span className="font-semibold">{reportMeta.generatedBy}</span> },
          { label: 'Generated at', value: <span className="font-semibold">{reportMeta.generatedAt}</span> },
        ]}
      />
    ) : null;

  const downloadCsv = () => {
    const lines = [
      [
        'S No.',
        'Status',
        'Agent Code',
        'Parent Agent',
        'Agent Name',
        'Agent Phone No',
        'Agent Address',
        'Max Credit Limit',
        'Allowed Credit Limit',
        'Agent Balance',
      ].join(','),
      ...rows.map((r, i) =>
        [
          i + 1,
          r.status === 1 ? 'Active' : 'Inactive',
          r.agentCode,
          r.parentAgent,
          r.agentName,
          r.agentPhoneNo,
          r.agentAddress,
          r.maxCreditLimit.toFixed(2),
          r.allowedCreditLimit.toFixed(2),
          r.agentBalance.toFixed(2),
        ]
          .map((v) => `"${String(v).replace(/"/g, '""')}"`)
          .join(',')
      ),
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `agent-balance-report-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full py-2 space-y-3">
      <Card>
        <CardHeader className="pb-2">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
            <div>
              <CardTitle className="text-xl font-bold">Agent Balance Report</CardTitle>
              <CardDescription className="text-xs mt-0.5">
                Agent balances from agencies and linked PAYABLE accounts.
              </CardDescription>
            </div>
            <div className="flex gap-2 no-print">
              <Button variant="outline" size="sm" onClick={() => window.print()} className="gap-2"><Printer />Print</Button>
              <Button variant="outline" size="sm" onClick={downloadCsv} className="gap-2"><Download />Download CSV</Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-wrap items-end gap-4 no-print">
            <ReportAgentSelect
              label="Select Agent"
              agentOptions={agentOptions}
              value={agentId}
              onChange={(v) => setAgentId(v ?? '__all__')}
            />
            <Selector
              label="All Status"
              options={STATUS_OPTIONS}
              value={status}
              onChange={setStatus}
              className={{ trigger: 'w-[180px]' }}
            />
            <Button size="sm" onClick={runSearch} disabled={loading} className="h-10 gap-2">
              <SearchIcon className="h-4 w-4" />Search
            </Button>
          </div>
        </CardContent>
      </Card>

      {!reportMeta && (
        <ReportEmptyStateCard
          title="Run a search to view results"
          description="Select filters and click Search."
        />
      )}

      {reportMeta && (
        <Card className="bg-muted/20">
          <CardHeader className="py-2">
            <CardTitle className="text-base">Agent Balance Report</CardTitle>
            <CardDescription className="text-xs mt-0.5">Agency soft/hard limits with live account balance.</CardDescription>
            {renderMetaCard()}
          </CardHeader>
          <CardContent className="space-y-3 py-2">
            {loading ? (
              <div className="text-center py-8">Loading...</div>
            ) : rows.length === 0 ? (
              <ReportEmptyStateCard
                title="No results"
                description="No agents found for the selected filters."
              />
            ) : (
              <>
                <div className="rounded-md border overflow-x-auto">
                  <Table className="text-[11px] [&_th]:px-1.5 [&_td]:px-1.5 [&_th]:border-r [&_th:last-child]:border-r-0 [&_td]:border-r [&_td:last-child]:border-r-0">
                    <TableHeader>
                      <TableRow className="border-b">
                        <TableHead className="w-10 text-right">No.</TableHead>
                        <TableHead>Status</TableHead>
                        <TableHead className="text-center">Agent Code</TableHead>
                        <TableHead>Parent Agent</TableHead>
                        <TableHead>Agent Name</TableHead>
                        <TableHead>Agent Phone No</TableHead>
                        <TableHead>Agent Address</TableHead>
                        <TableHead className="text-right">Max Credit Limit</TableHead>
                        <TableHead className="text-right">Allowed Credit Limit</TableHead>
                        <TableHead className="text-right">Agent Balance</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {rows.map((r, i) => (
                        <TableRow key={r.id} className="border-b border-border/50">
                          <TableCell className="text-center tabular-nums">{i + 1}</TableCell>
                          <TableCell>
                            <span
                              className={
                                r.status === 1
                                  ? 'inline-flex items-center rounded px-2 py-0.5 text-[10px] font-medium bg-emerald-50 text-emerald-700'
                                  : 'inline-flex items-center rounded px-2 py-0.5 text-[10px] font-medium bg-red-100/70 text-red-700'
                              }
                            >
                              {r.status === 1 ? 'Active' : 'Inactive'}
                            </span>
                          </TableCell>
                          <TableCell className="text-center">{r.agentCode}</TableCell>
                          <TableCell>{r.parentAgent}</TableCell>
                          <TableCell>{r.agentName}</TableCell>
                          <TableCell>{r.agentPhoneNo}</TableCell>
                          <TableCell>{r.agentAddress}</TableCell>
                          <TableCell className="text-right tabular-nums">{formatLKR(r.maxCreditLimit)}</TableCell>
                          <TableCell className="text-right tabular-nums">{formatLKR(r.allowedCreditLimit)}</TableCell>
                          <TableCell className="text-right tabular-nums">{formatLKR(r.agentBalance)}</TableCell>
                        </TableRow>
                      ))}
                      <TableRow className="font-medium bg-muted/50">
                        <TableCell colSpan={9}>Total</TableCell>
                        <TableCell className="text-right tabular-nums">{formatLKR(balanceTotal)}</TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </div>
                {renderMetaCard()}
              </>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
