export type DoctorLeaveReportRow = {
  /** Unique row id (leaveId + sessionId) */
  id: string;
  /** DoctorLeave id */
  leaveId: string;
  /** Session id that is on leave */
  sessionId: string;
  /** Leave date (session date) */
  leaveDate: Date;
  /** Session start/end time for the leave date */
  sessionStartTime?: Date;
  sessionEndTime?: Date;
  status: number;
  remarks: string | null;
  doctor: { id: string; name: string; code: string };
  /** Single session display text (day + time range) */
  leaveSessionFormatted?: string;
  createdUser?: { id: string; name: string; staff?: { code: string } | null } | null;
  updatedUser?: { id: string; name: string; staff?: { code: string } | null } | null;
  createdAt: Date;
  updatedAt: Date;
};

/** Report query params for doctor leave report */
export type DoctorLeaveReportQuery = {
  fromDateTime?: string; // YYYY-MM-DD or YYYY-MM-DDTHH:mm
  toDateTime?: string;
  institutionId?: string;
  locationId?: string;
  departmentId?: string;
  specialityId?: string;
  doctorId?: string;
};

export type DoctorLeaveReportExportRow = {
  doctorCode: string;
  doctorName: string;
  leaveDate: string;
  leaveSessions: string;
  leaveRemark: string;
  leaveCreator: string;
  leaveCreatorAt: string;
  leaveUpdator: string;
  leaveUpdatorAt: string;
  status: string;
};

export type DoctorLeaveReportContentProps = {
  /** Display name for "Generated by" in report generation details. */
  currentUserName: string;
  institutionOptions: Array<{ id: string; name: string }>;
  locationOptions: Array<{ id: string; name: string }>;
  departmentOptions: Array<{ id: string; name: string }>;
  specialityOptions: Array<{ id: string; name: string }>;
  doctorOptions: Array<{ id: string; name: string }>;
};