import { format } from "date-fns"
import type { ReceiptTemplateData } from "@/types/receipt-template"
import type { LedgerReceiptDetail } from "@/services/ledger/get-ledger-receipt.service"

export type LedgerReceiptTemplateOptions = {
  /** Company/brand name for header (e.g. "RH Channel"). Defaults to location name if not set. */
  companyName?: string
  /** Optional location line (e.g. "Ruhunu Hospital, Karapitiya, Galle"). */
  locationLine?: string
  tel?: string
  email?: string
  web?: string
  /** Override "Generated By" text; if not set, uses receipt.createdByName and createdById. */
  generatedBy?: string
  /** Override generated at date; if not set, uses current date/time. */
  generatedAt?: string
}

/**
 * Build receipt template data from a ledger receipt (like filling SMS template placeholders).
 * Use with <ReceiptTemplate data={...} /> for a consistent Debit Note / Expenses Note style layout.
 */
export function buildLedgerReceiptTemplateData(
  receipt: LedgerReceiptDetail,
  options: LedgerReceiptTemplateOptions = {}
): ReceiptTemplateData {
  const locationName = receipt.locationName ?? ""
  const companyName = options.companyName ?? locationName ?? "Ledger"
  const locationLine = options.locationLine ?? locationName
  const dateTime = format(new Date(receipt.createdAt), "yyyy-MM-dd hh:mm a")
  const amountStr = receipt.amount.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })
  const comment =
    receipt.remarks ||
    (receipt.bank ? `Bank: ${receipt.bank}` : "") ||
    (receipt.agencyName ? `Agency: ${receipt.agencyName}` : "")

  const generatedBy =
    options.generatedBy ??
    (receipt.createdByName && receipt.createdById
      ? `${receipt.createdByName} (${receipt.createdById})`
      : undefined)
  const generatedAt =
    options.generatedAt ?? format(new Date(), "dd/MM/yyyy HH.mm")

  const hasAgency = !!(receipt.agencyName || receipt.agencyCode)
  const columns = hasAgency
    ? [
        { key: "receiptNo", label: "Receipt No" },
        { key: "agentName", label: "Agent Name" },
        { key: "comment", label: "Comment" },
        { key: "transactionType", label: "Transaction Type" },
        { key: "amount", label: "Amount (Rs)" },
      ]
    : [
        { key: "receiptNo", label: "Receipt No" },
        { key: "comment", label: "Comment" },
        { key: "transactionType", label: "Transaction Type" },
        { key: "amount", label: "Amount (Rs)" },
      ]

  const row: Record<string, string> = {
    receiptNo: receipt.receiptNoString,
    comment: comment.trim() || "—",
    transactionType: receipt.paymentMethodName,
    amount: amountStr,
  }
  if (hasAgency) {
    row.agentName =
      receipt.agencyCode && receipt.agencyName
        ? `${receipt.agencyName} (${receipt.agencyCode})`
        : receipt.agencyName ?? "—"
  }

  return {
    header: {
      companyName,
      locationName: locationLine || undefined,
      tel: options.tel,
      email: options.email,
      web: options.web,
    },
    title: receipt.methodName,
    dateTime,
    table: {
      columns,
      rows: [row],
      totalLabel: "Total",
      totalAmountKey: "amount",
      totalLabelColumnKey: "transactionType",
    },
    remarks: receipt.remarks || undefined,
    generatedBy,
    generatedAt,
  }
}
