import { replacePlaceholders } from "./replace-placeholders"
import type { ReceiptPlaceholderMap } from "@/types/receipt-template-db"
import type { ReceiptTemplateRecord } from "@/types/receipt-template-db"
import type { LedgerReceiptDetail } from "@/services/ledger/get-ledger-receipt.service"
import { format } from "date-fns"

const PRINT_PAGE_STYLES = `
  body { font-family: system-ui, sans-serif; font-size: 14px; line-height: 1.4; color: #111; padding: 16px; max-width: 210mm; margin: 0 auto; }
  .receipt-header { text-align: center; margin-bottom: 1rem; font-weight: 600; white-space: pre-wrap; }
  .receipt-body { white-space: pre-wrap; margin-bottom: 1rem; }
  .receipt-footer { font-size: 12px; color: #555; border-top: 1px solid #ddd; padding-top: 0.75rem; margin-top: 1rem; white-space: pre-wrap; }
  .row { margin: 0.25rem 0; }
  .label { font-weight: 500; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; margin: 0.5rem 0; }
  th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }
  th { background: #f5f5f5; font-weight: 600; }
`

/**
 * Build full HTML document string for receipt print (template-based or fallback).
 * Used to open a new window and print only the receipt, avoiding main page CSS/layout.
 */
export function buildReceiptPrintHtml(
  receipt: LedgerReceiptDetail,
  placeholders: ReceiptPlaceholderMap,
  template: ReceiptTemplateRecord | null
): string {
  let bodyContent: string

  if (template) {
    const headerHtml = template.headerTemplate
      ? replacePlaceholders(template.headerTemplate.content, placeholders)
      : ""
    const bodyHtml = replacePlaceholders(template.bodyContent, placeholders)
    const footerHtml = template.footerTemplate
      ? replacePlaceholders(template.footerTemplate.content, placeholders)
      : ""
    // Insert as plain text (newlines preserved via white-space: pre-wrap); escape so template content doesn't break HTML
    bodyContent = `
    ${headerHtml ? `<div class="receipt-header">${escapeHtml(headerHtml)}</div>` : ""}
    <div class="receipt-body">${escapeHtml(bodyHtml)}</div>
    ${footerHtml ? `<div class="receipt-footer">${escapeHtml(footerHtml)}</div>` : ""}
    `
  } else {
    bodyContent = buildFallbackReceiptHtml(receipt)
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Receipt ${escapeHtml(receipt.receiptNoString)}</title>
  <style>${PRINT_PAGE_STYLES}</style>
</head>
<body>
${bodyContent}
</body>
</html>`
}

function escapeHtml(text: string): string {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function buildFallbackReceiptHtml(receipt: LedgerReceiptDetail): string {
  const branch = receipt.locationName ?? "—"
  const agency = receipt.agencyName
    ? receipt.agencyCode
      ? `${receipt.agencyName} (${receipt.agencyCode})`
      : receipt.agencyName
    : "—"
  const dateStr = format(new Date(receipt.createdAt), "dd MMM yyyy HH:mm")
  const amountStr = receipt.amount.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })
  const generatedBy =
    receipt.createdByName && receipt.createdById
      ? `${receipt.createdByName} (${receipt.createdById})`
      : "—"
  const generatedAt = format(new Date(), "dd/MM/yyyy HH.mm")

  return `
  <div class="receipt-header">${escapeHtml(receipt.methodName)}</div>
  <div class="receipt-body">
    <div class="row"><span class="label">Date/Time:</span> ${escapeHtml(dateStr)}</div>
    <div class="row"><span class="label">Receipt No:</span> ${escapeHtml(receipt.receiptNoString)}</div>
    <div class="row"><span class="label">Branch:</span> ${escapeHtml(branch)}</div>
    <div class="row"><span class="label">Transaction Type:</span> ${escapeHtml(receipt.paymentMethodName)}</div>
    <div class="row"><span class="label">Amount (Rs):</span> ${escapeHtml(amountStr)}</div>
    <div class="row"><span class="label">Remarks:</span> ${escapeHtml(receipt.remarks || "—")}</div>
    ${receipt.agencyName ? `<div class="row"><span class="label">Agency:</span> ${escapeHtml(agency)}</div>` : ""}
    ${receipt.bank ? `<div class="row"><span class="label">Bank:</span> ${escapeHtml(receipt.bank)}</div>` : ""}
  </div>
  <div class="receipt-footer">
    <div class="row">Generated By: ${escapeHtml(generatedBy)}</div>
    <div class="row">${escapeHtml(generatedAt)}</div>
  </div>
  `
}
