import { replacePlaceholders } from "./replace-placeholders"
import type { ReceiptPlaceholderMap } from "@/types/receipt-template-db"
import type { ReceiptTemplateRecord } from "@/types/receipt-template-db"
import type { LedgerReceiptDetail } from "@/services/ledger/get-ledger-receipt.service"
import { format } from "date-fns"

const PRINT_PAGE_STYLES = `
  body { font-family: system-ui, sans-serif; font-size: 14px; line-height: 1.4; color: #111; padding: 16px; max-width: 210mm; margin: 0 auto; }
  .receipt-header { text-align: center; margin-bottom: 1rem; font-weight: 600; white-space: pre-wrap; }
  .receipt-body { white-space: pre-wrap; margin-bottom: 1rem; }
  .receipt-footer { font-size: 12px; color: #555; border-top: 1px solid #ddd; padding-top: 0.75rem; margin-top: 1rem; white-space: pre-wrap; }
  .row { margin: 0.25rem 0; }
  .label { font-weight: 500; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; margin: 0.5rem 0; }
  th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }
  th { background: #f5f5f5; font-weight: 600; }
`

/**
 * Build full HTML document string for receipt print (template-based or fallback).
 * Used to open a new window and print only the receipt, avoiding main page CSS/layout.
 */
export function buildReceiptPrintHtml(
  receipt: LedgerReceiptDetail,
  placeholders: ReceiptPlaceholderMap,
  template: ReceiptTemplateRecord | null
): string {
  let bodyContent: string

  if (template) {
    const headerHtml = template.headerTemplate
      ? replacePlaceholders(template.headerTemplate.content, placeholders)
      : ""
    const bodyHtml = replacePlaceholders(template.bodyContent, placeholders)
    const footerHtml = template.footerTemplate
      ? replacePlaceholders(template.footerTemplate.content, placeholders)
      : ""
    // Insert as plain text (newlines preserved via white-space: pre-wrap); escape so template content doesn't break HTML
    bodyContent = `
    ${headerHtml ? `<div class="receipt-header">${escapeHtml(headerHtml)}</div>` : ""}
    <div class="receipt-body">${escapeHtml(bodyHtml)}</div>
    ${footerHtml ? `<div class="receipt-footer">${escapeHtml(footerHtml)}</div>` : ""}
    `
  } else {
    bodyContent = buildFallbackReceiptHtml(receipt)
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Receipt ${escapeHtml(receipt.receiptNoString)}</title>
  <style>${PRINT_PAGE_STYLES}</style>
</head>
<body>
${bodyContent}
</body>
</html>`
}

function escapeHtml(text: string): string {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function buildFallbackReceiptHtml(receipt: LedgerReceiptDetail): string {
  const branch = receipt.locationName ?? "—"
  const agency = receipt.agencyName
    ? receipt.agencyCode
      ? `${receipt.agencyName} (${receipt.agencyCode})`
      : receipt.agencyName
    : "—"
  const dateStr = format(new Date(receipt.createdAt), "dd MMM yyyy HH:mm")
  const amountStr = receipt.amount.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })
  const generatedBy =
    receipt.createdByName && receipt.createdById
      ? `${receipt.createdByName} (${receipt.createdById})`
      : "—"
  const generatedAt = format(new Date(), "dd/MM/yyyy HH.mm")

  return `
  <div class="receipt-header">${escapeHtml(receipt.methodName)}</div>
  <div class="receipt-body">
    <div class="row"><span class="label">Date/Time:</span> ${escapeHtml(dateStr)}</div>
    <div class="row"><span class="label">Receipt No:</span> ${escapeHtml(receipt.receiptNoString)}</div>
    <div class="row"><span class="label">Branch:</span> ${escapeHtml(branch)}</div>
    <div class="row"><span class="label">Transaction Type:</span> ${escapeHtml(receipt.paymentMethodName)}</div>
    <div class="row"><span class="label">Amount (Rs):</span> ${escapeHtml(amountStr)}</div>
    <div class="row"><span class="label">Remarks:</span> ${escapeHtml(receipt.remarks || "—")}</div>
    ${receipt.agencyName ? `<div class="row"><span class="label">Agency:</span> ${escapeHtml(agency)}</div>` : ""}
    ${receipt.bank ? `<div class="row"><span class="label">Bank:</span> ${escapeHtml(receipt.bank)}</div>` : ""}
  </div>
  <div class="receipt-footer">
    <div class="row">Generated By: ${escapeHtml(generatedBy)}</div>
    <div class="row">${escapeHtml(generatedAt)}</div>
  </div>
  `
}

/**
 * Build full HTML for doctor payment (Consultant Payment) receipt print from placeholders and template.
 */
export function buildDoctorPaymentPrintHtml(
  placeholders: ReceiptPlaceholderMap,
  template: ReceiptTemplateRecord | null,
  receiptNoString: string
): string {
  let bodyContent: string
  if (template) {
    const headerHtml = template.headerTemplate
      ? replacePlaceholders(template.headerTemplate.content, placeholders)
      : ""
    const bodyHtml = replacePlaceholders(template.bodyContent, placeholders)
    const footerHtml = template.footerTemplate
      ? replacePlaceholders(template.footerTemplate.content, placeholders)
      : ""
    bodyContent = `
    ${headerHtml ? `<div class="receipt-header">${escapeHtml(headerHtml)}</div>` : ""}
    <div class="receipt-body">${escapeHtml(bodyHtml)}</div>
    ${footerHtml ? `<div class="receipt-footer">${escapeHtml(footerHtml)}</div>` : ""}
    `
  } else {
    bodyContent = `
    <div class="receipt-header">Consultant Payment</div>
    <div class="receipt-body">
      <div class="row"><span class="label">Invoice No:</span> ${escapeHtml(placeholders.invoice_no ?? "")}</div>
      <div class="row"><span class="label">Consultant:</span> ${escapeHtml(placeholders.consultant_name ?? "")}</div>
      <div class="row"><span class="label">Net Paid Amount:</span> ${escapeHtml(placeholders.net_paid_amount ?? "")}</div>
      <div class="row"><span class="label">Paid On:</span> ${escapeHtml(placeholders.paid_on ?? "")}</div>
      <div class="row"><span class="label">Generated By:</span> ${escapeHtml(placeholders.generated_by ?? "")}</div>
    </div>
    <div class="receipt-footer">${escapeHtml(placeholders.generated_at ?? "")}</div>
    `
  }
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Consultant Payment ${escapeHtml(receiptNoString)}</title>
  <style>${PRINT_PAGE_STYLES}</style>
</head>
<body>
${bodyContent}
</body>
</html>`
}

const BOOKING_RECEIPT_PAGE_STYLES = `
  @page { size: A5 portrait; margin: 4mm 12mm; }
  html, body { margin: 0; padding: 0; }
  body {
    font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
    font-size: 11px;
    line-height: 1.35;
    color: #000;
    padding: 0 3mm;
    background: #fff;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
  }
  .duplicate-banner {
    text-align: center;
    font-weight: 700;
    letter-spacing: 0.18em;
    font-size: 14px;
    margin: 0 0 8px;
  }
  .watermark {
    position: fixed;
    top: 38%;
    left: 50%;
    transform: translate(-50%, -50%) rotate(-28deg);
    font-size: 56px;
    font-weight: 700;
    letter-spacing: 0.12em;
    color: #000;
    opacity: 0.08;
    pointer-events: none;
    white-space: nowrap;
    z-index: 0;
  }
  .receipt-header { text-align: center; margin-bottom: 0.6rem; font-weight: 600; white-space: pre-wrap; position: relative; z-index: 1; }
  .receipt-body { white-space: pre-wrap; margin-bottom: 0.6rem; position: relative; z-index: 1; }
  .receipt-footer { font-size: 10px; color: #333; border-top: 1px solid #000; padding-top: 0.5rem; margin-top: 0.6rem; white-space: pre-wrap; position: relative; z-index: 1; }
  .sails-table { width: 100%; border-collapse: collapse; position: relative; z-index: 1; }
  .sails-table td { border: 1px solid #000; padding: 4px 6px; vertical-align: top; }
  .sails-table .label { font-weight: 600; width: 22%; }
  .sails-table .value { width: 28%; }
  .sails-table .highlight { font-weight: 700; color: #b91c1c; }
  .refund-row td { font-weight: 600; }
`

function bookingReceiptCell(label: string, value: string, highlight = false): string {
  const valueClass = highlight ? "value highlight" : "value"
  return `<td class="label">${escapeHtml(label)}</td><td class="${valueClass}">${escapeHtml(value)}</td>`
}

function buildFallbackBookingReceiptHtml(placeholders: ReceiptPlaceholderMap): string {
  const refundAmount = (placeholders.refund_amount ?? "").trim()
  const refundReceiptNo = (placeholders.refund_receipt_no ?? "").trim()
  const refundReason = (placeholders.refund_reason ?? "").trim()
  const refundRows =
    refundAmount || refundReceiptNo || refundReason
      ? `
    <tr class="refund-row">${bookingReceiptCell("Refund Amount", refundAmount || "—")}${bookingReceiptCell("Refund Receipt", refundReceiptNo || "—")}</tr>
    ${refundReason ? `<tr class="refund-row">${bookingReceiptCell("Cancel / refund remark", refundReason)}<td class="label"></td><td class="value"></td></tr>` : ""}
      `
      : ""

  return `
  <table class="sails-table">
    <tr>${bookingReceiptCell("Name", placeholders.patient_name ?? "")}${bookingReceiptCell("Bill No", placeholders.bill_no ?? "")}</tr>
    <tr>${bookingReceiptCell("Consultant", placeholders.consultant ?? "")}${bookingReceiptCell("Bill Sub Total", placeholders.bill_sub_total ?? "")}</tr>
    <tr>${bookingReceiptCell("Appo. No", placeholders.appointment_no ?? "", true)}${bookingReceiptCell("Discount", placeholders.discount ?? "")}</tr>
    <tr>${bookingReceiptCell("Appointment Date", placeholders.appointment_date ?? "")}${bookingReceiptCell("Bill Total", placeholders.bill_total ?? "", true)}</tr>
    <tr>${bookingReceiptCell("Appointment Time", placeholders.appointment_time ?? "")}${bookingReceiptCell("Billed By", placeholders.billed_by ?? "")}</tr>
    <tr>${bookingReceiptCell("Tel", placeholders.phone ?? placeholders.tel ?? "")}${bookingReceiptCell("Remark", placeholders.remarks ?? "")}</tr>
    <tr>${bookingReceiptCell("Booking Method", placeholders.booking_method ?? "")}${bookingReceiptCell("Area", placeholders.area ?? "")}</tr>
    ${refundRows}
  </table>
  `
}

/**
 * Build full HTML for booking (Sails-style) receipt print. A5 portrait.
 */
export function buildBookingReceiptPrintHtml(
  placeholders: ReceiptPlaceholderMap,
  template: ReceiptTemplateRecord | null,
  receiptNoString: string
): string {
  const duplicateLabel = (placeholders.duplicate_label ?? "").trim()
  const isDuplicate = duplicateLabel.length > 0
  let bodyContent: string

  if (template) {
    const headerHtml = template.headerTemplate
      ? replacePlaceholders(template.headerTemplate.content, placeholders)
      : ""
    const bodyHtml = replacePlaceholders(template.bodyContent, placeholders)
    const footerHtml = template.footerTemplate
      ? replacePlaceholders(template.footerTemplate.content, placeholders)
      : ""
    bodyContent = `
    ${headerHtml ? `<div class="receipt-header">${escapeHtml(headerHtml)}</div>` : ""}
    <div class="receipt-body">${escapeHtml(bodyHtml)}</div>
    ${footerHtml ? `<div class="receipt-footer">${escapeHtml(footerHtml)}</div>` : ""}
    `
  } else {
    bodyContent = buildFallbackBookingReceiptHtml(placeholders)
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Receipt ${escapeHtml(receiptNoString)}</title>
  <style>${BOOKING_RECEIPT_PAGE_STYLES}</style>
</head>
<body>
${isDuplicate ? `<div class="watermark">${escapeHtml(duplicateLabel)}</div>` : ""}
${isDuplicate && !template ? `<p class="duplicate-banner">${escapeHtml(duplicateLabel)}</p>` : ""}
${bodyContent}
</body>
</html>`
}
