import { replacePlaceholders } from "./replace-placeholders"
import type { ReceiptPlaceholderMap } from "@/types/receipt-template-db"
import type { ReceiptTemplateRecord } from "@/types/receipt-template-db"
import type { LedgerReceiptDetail } from "@/services/ledger/get-ledger-receipt.service"
import { format } from "date-fns"
import {
  RUHUNU_HOSPITAL,
  ruhunuEmailWebLine,
  ruhunuPhoneFaxLine,
} from "@/lib/receipt-template/ruhunu-hospital"

const PRINT_PAGE_STYLES = `
  body { font-family: system-ui, sans-serif; font-size: 14px; line-height: 1.4; color: #111; padding: 16px; max-width: 210mm; margin: 0 auto; }
  .receipt-header { text-align: center; margin-bottom: 1rem; font-weight: 600; white-space: pre-wrap; }
  .receipt-body { white-space: pre-wrap; margin-bottom: 1rem; }
  .receipt-footer { font-size: 12px; color: #555; border-top: 1px solid #ddd; padding-top: 0.75rem; margin-top: 1rem; white-space: pre-wrap; }
  .row { margin: 0.25rem 0; }
  .label { font-weight: 500; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; margin: 0.5rem 0; }
  th, td { border: 1px solid #ddd; padding: 6px 8px; text-align: left; }
  th { background: #f5f5f5; font-weight: 600; }
`

/**
 * Build full HTML document string for receipt print (template-based or fallback).
 * Used to open a new window and print only the receipt, avoiding main page CSS/layout.
 */
export function buildReceiptPrintHtml(
  receipt: LedgerReceiptDetail,
  placeholders: ReceiptPlaceholderMap,
  template: ReceiptTemplateRecord | null
): string {
  let bodyContent: string

  if (template) {
    const headerHtml = template.headerTemplate
      ? replacePlaceholders(template.headerTemplate.content, placeholders)
      : ""
    const bodyHtml = replacePlaceholders(template.bodyContent, placeholders)
    const footerHtml = template.footerTemplate
      ? replacePlaceholders(template.footerTemplate.content, placeholders)
      : ""
    // Insert as plain text (newlines preserved via white-space: pre-wrap); escape so template content doesn't break HTML
    bodyContent = `
    ${headerHtml ? `<div class="receipt-header">${escapeHtml(headerHtml)}</div>` : ""}
    <div class="receipt-body">${escapeHtml(bodyHtml)}</div>
    ${footerHtml ? `<div class="receipt-footer">${escapeHtml(footerHtml)}</div>` : ""}
    `
  } else {
    bodyContent = buildFallbackReceiptHtml(receipt)
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Receipt ${escapeHtml(receipt.receiptNoString)}</title>
  <style>${PRINT_PAGE_STYLES}</style>
</head>
<body>
${bodyContent}
</body>
</html>`
}

function escapeHtml(text: string): string {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function buildFallbackReceiptHtml(receipt: LedgerReceiptDetail): string {
  const branch = receipt.locationName ?? "—"
  const agency = receipt.agencyName
    ? receipt.agencyCode
      ? `${receipt.agencyName} (${receipt.agencyCode})`
      : receipt.agencyName
    : "—"
  const dateStr = format(new Date(receipt.createdAt), "dd MMM yyyy HH:mm")
  const amountStr = receipt.amount.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })
  const generatedBy =
    receipt.createdByName && receipt.createdById
      ? `${receipt.createdByName} (${receipt.createdById})`
      : "—"
  const generatedAt = format(new Date(), "dd/MM/yyyy HH.mm")

  return `
  <div class="receipt-header">${escapeHtml(receipt.methodName)}</div>
  <div class="receipt-body">
    <div class="row"><span class="label">Date/Time:</span> ${escapeHtml(dateStr)}</div>
    <div class="row"><span class="label">Receipt No:</span> ${escapeHtml(receipt.receiptNoString)}</div>
    <div class="row"><span class="label">Branch:</span> ${escapeHtml(branch)}</div>
    <div class="row"><span class="label">Transaction Type:</span> ${escapeHtml(receipt.paymentMethodName)}</div>
    <div class="row"><span class="label">Amount (Rs):</span> ${escapeHtml(amountStr)}</div>
    <div class="row"><span class="label">Remarks:</span> ${escapeHtml(receipt.remarks || "—")}</div>
    ${receipt.agencyName ? `<div class="row"><span class="label">Agency:</span> ${escapeHtml(agency)}</div>` : ""}
    ${receipt.bank ? `<div class="row"><span class="label">Bank:</span> ${escapeHtml(receipt.bank)}</div>` : ""}
  </div>
  <div class="receipt-footer">
    <div class="row">Generated By: ${escapeHtml(generatedBy)}</div>
    <div class="row">${escapeHtml(generatedAt)}</div>
  </div>
  `
}

/**
 * Build full HTML for doctor payment (Consultant Payment) receipt print from placeholders and template.
 */
export function buildDoctorPaymentPrintHtml(
  placeholders: ReceiptPlaceholderMap,
  template: ReceiptTemplateRecord | null,
  receiptNoString: string
): string {
  let bodyContent: string
  if (template) {
    const headerHtml = template.headerTemplate
      ? replacePlaceholders(template.headerTemplate.content, placeholders)
      : ""
    const bodyHtml = replacePlaceholders(template.bodyContent, placeholders)
    const footerHtml = template.footerTemplate
      ? replacePlaceholders(template.footerTemplate.content, placeholders)
      : ""
    bodyContent = `
    ${headerHtml ? `<div class="receipt-header">${escapeHtml(headerHtml)}</div>` : ""}
    <div class="receipt-body">${escapeHtml(bodyHtml)}</div>
    ${footerHtml ? `<div class="receipt-footer">${escapeHtml(footerHtml)}</div>` : ""}
    `
  } else {
    bodyContent = `
    <div class="receipt-header">Consultant Payment</div>
    <div class="receipt-body">
      <div class="row"><span class="label">Invoice No:</span> ${escapeHtml(placeholders.invoice_no ?? "")}</div>
      <div class="row"><span class="label">Consultant:</span> ${escapeHtml(placeholders.consultant_name ?? "")}</div>
      <div class="row"><span class="label">Net Paid Amount:</span> ${escapeHtml(placeholders.net_paid_amount ?? "")}</div>
      <div class="row"><span class="label">Paid On:</span> ${escapeHtml(placeholders.paid_on ?? "")}</div>
      <div class="row"><span class="label">Generated By:</span> ${escapeHtml(placeholders.generated_by ?? "")}</div>
    </div>
    <div class="receipt-footer">${escapeHtml(placeholders.generated_at ?? "")}</div>
    `
  }
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Consultant Payment ${escapeHtml(receiptNoString)}</title>
  <style>${PRINT_PAGE_STYLES}</style>
</head>
<body>
${bodyContent}
</body>
</html>`
}

const BOOKING_RECEIPT_PAGE_STYLES = `
  /* Dot matrix / tractor-feed: use the printer's paper, do not shrink to A5. */
  @page { margin: 8mm 10mm; }
  html, body { margin: 0; padding: 0; width: 100%; background: #fff; }
  * { color: #000 !important; background: transparent !important; box-shadow: none !important; }
  body {
    font-family: Verdana, Geneva, sans-serif;
    font-size: 33px;
    line-height: 1.25;
    color: #000;
    padding: 2mm 4mm;
  }
  .invoice-wrap { text-align: center; }
  .hospital-name {
    font-size: 40px;
    font-weight: 700;
    margin: 0;
    line-height: 1.2;
  }
  .contact {
    font-size: 26px;
    font-weight: 700;
    margin: 2px 0 0;
    line-height: 1.3;
  }
  .bill-title {
    font-size: 40px;
    font-weight: 700;
    margin: 10px 0 4px;
  }
  .status-banner {
    font-size: 34px;
    font-weight: 700;
    margin: 4px 0 8px;
  }
  .invoice-fields {
    margin: 0 auto;
    border-collapse: collapse;
    text-align: left;
  }
  .invoice-fields td {
    border: none;
    padding: 4px 0;
    font-size: 33px;
    vertical-align: top;
  }
  .invoice-fields .label { min-width: 390px; padding-right: 8px; }
  .invoice-fields .colon { padding-right: 8px; }
  .invoice-fields .value { font-weight: 400; }
  .invoice-fields .strong { font-weight: 700; }
  .appt-no {
    font-size: 70px;
    font-weight: 700;
    padding-left: 15px;
    line-height: 1;
  }
  .professional-bill { margin-top: 36px; padding-top: 12px; }
  .doctor-note {
    font-size: 31px;
    font-weight: 700;
    text-align: center;
    margin: 36px 0 0;
  }
`

function invoiceRow(
  label: string,
  value: string,
  opts: { strongLabel?: boolean; strongValue?: boolean; huge?: boolean } = {}
): string {
  const labelHtml = opts.strongLabel ? `<strong>${escapeHtml(label)}</strong>` : escapeHtml(label)
  const valueClass = opts.strongValue ? "value strong" : "value"
  const valueHtml = opts.huge
    ? `<span class="appt-no">${escapeHtml(value)}</span>`
    : escapeHtml(value)
  return `<tr>
    <td class="label">${labelHtml}</td>
    <td class="colon">:</td>
    <td class="${valueClass}">${valueHtml}</td>
  </tr>`
}

function buildSailsBookingReceiptHtml(placeholders: ReceiptPlaceholderMap): string {
  const statusBanner = (placeholders.status_banner ?? "").trim()
  const hospitalDiscount = (placeholders.hospital_fee_discount ?? "").trim()
  const professionalDiscount = (placeholders.professional_fee_discount ?? "").trim()
  const refundReceiptNo = (placeholders.refund_receipt_no ?? "").trim()
  const debiter = (placeholders.debiter ?? "").trim()
  const showProfessional = (placeholders.show_professional_bill ?? "").trim() === "1"
  const companyName = placeholders.company_name || RUHUNU_HOSPITAL.name
  const locationAddress = placeholders.location_address || RUHUNU_HOSPITAL.address

  const hospitalRows = [
    invoiceRow("Number", placeholders.appointment_no ?? "", { strongLabel: true, huge: true }),
    invoiceRow("Name", placeholders.patient_name ?? ""),
    refundReceiptNo ? invoiceRow("Refund Invoice No", refundReceiptNo) : "",
    invoiceRow("Invoice No", placeholders.bill_no ?? ""),
    invoiceRow("Phone", placeholders.phone ?? placeholders.tel ?? ""),
    invoiceRow("Appointment Type", placeholders.booking_method ?? ""),
    invoiceRow("App. Date", placeholders.appointment_date ?? "", { strongLabel: true, strongValue: true }),
    invoiceRow("App. Time", placeholders.appointment_time ?? "", { strongLabel: true, strongValue: true }),
    invoiceRow("Hospital Fee", placeholders.hospital_fee ?? ""),
    hospitalDiscount ? invoiceRow("Discount", hospitalDiscount) : "",
    invoiceRow("Total Hospital Fee", placeholders.total_hospital_fee ?? "", {
      strongLabel: true,
      strongValue: true,
    }),
    invoiceRow("Billed At", placeholders.billed_at ?? ""),
    invoiceRow("Cashier Code", placeholders.cashier_code ?? ""),
    invoiceRow("Invoice Status", placeholders.invoice_status ?? ""),
    debiter ? invoiceRow("Debiter", debiter) : "",
    invoiceRow("Printed by", placeholders.printed_by ?? ""),
  ]
    .filter(Boolean)
    .join("")

  const professionalRows = [
    invoiceRow("Name", placeholders.patient_name ?? ""),
    invoiceRow("Invoice Ref", placeholders.bill_no ?? ""),
    invoiceRow("Consultant", placeholders.consultant ?? "", { strongLabel: true, strongValue: true }),
    invoiceRow("Professional Charges", placeholders.professional_fee ?? ""),
    professionalDiscount ? invoiceRow("Discount", professionalDiscount) : "",
    professionalDiscount
      ? invoiceRow("Total Professional Fee", placeholders.total_professional_fee ?? "")
      : "",
  ]
    .filter(Boolean)
    .join("")

  const statusHtml = statusBanner
    ? `<div class="status-banner">${escapeHtml(statusBanner)}</div>`
    : ""

  return `
  <div class="invoice-wrap">
    <div class="hospital-name">${escapeHtml(companyName)}</div>
    <div class="hospital-name">${escapeHtml(locationAddress)}</div>
    <p class="contact">${escapeHtml(ruhunuPhoneFaxLine())}</p>
    <p class="contact">${escapeHtml(ruhunuEmailWebLine())}</p>
    <div class="bill-title">Invoice - Hospital Bill</div>
    ${statusHtml}
    <table class="invoice-fields"><tbody>${hospitalRows}</tbody></table>
    ${
      showProfessional
        ? `<div class="professional-bill">
      <div class="bill-title">Professional Bill</div>
      ${statusHtml}
      <table class="invoice-fields"><tbody>${professionalRows}</tbody></table>
      <p class="doctor-note">Collected for and on behalf of the Doctor*</p>
    </div>`
        : ""
    }
  </div>
  `
}

/**
 * Build full HTML for booking receipt print.
 * Sized for a graphics-capable dot-matrix on tractor-feed paper (same look as Sails).
 */
export function buildBookingReceiptPrintHtml(
  placeholders: ReceiptPlaceholderMap,
  _template: ReceiptTemplateRecord | null,
  receiptNoString: string
): string {
  const bodyContent = buildSailsBookingReceiptHtml(placeholders)

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Receipt ${escapeHtml(receiptNoString)}</title>
  <style>${BOOKING_RECEIPT_PAGE_STYLES}</style>
</head>
<body>
${bodyContent}
</body>
</html>`
}
