'use client';

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { DateTimeRangePicker } from '@/components/common/date-time-range-picker';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/components/hooks/use-toast';
import { Download, Printer, SearchIcon } from 'lucide-react';
import { getAllCashierSummaryDetailReportData } from '@/app/actions/reports/all-cashier-summary-detail.action';
import { formatReceiptAmount } from '@/lib/format-money';
import { SearchableUserSelect } from '@/components/common/searchable-user-select';
import type {
  AllCashierUserDetailRow,
  AllCashierUserSummaryRow,
  CashierSummaryPaymentAmounts,
} from '@/types/report';

type Props = {
  initialUserOptions: Array<{ id: string; name: string }>;
  initialLocationOptions: Array<{ id: string; name: string }>;
  currentUserName: string;
};

const PAYMENT_COLUMNS: { key: keyof CashierSummaryPaymentAmounts; label: string }[] = [
  { key: 'cash', label: 'Cash' },
  { key: 'creditCard', label: 'Credit Card' },
  { key: 'slip', label: 'Slip' },
  { key: 'cheque', label: 'Cheque' },
  { key: 'agent', label: 'Agent' },
  { key: 'agentCredit', label: 'Credit' },
  { key: 'eWallet', label: 'E-wallet' },
];

function formatAmount(n: number | undefined | null): string {
  const num = Number(n);
  if (!Number.isFinite(num)) return '0.00';
  return formatReceiptAmount(num);
}

function getDefaultDateTimeRange(): { from: string; to: string } {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  return { from: `${y}-${m}-${d}T00:00`, to: `${y}-${m}-${d}T23:59` };
}

export default function AllCashierSummaryDetailContent({
  initialUserOptions,
  initialLocationOptions,
  currentUserName,
}: Props) {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [fromDateTime, setFromDateTime] = useState<string>(() => getDefaultDateTimeRange().from);
  const [toDateTime, setToDateTime] = useState<string>(() => getDefaultDateTimeRange().to);
  const [userId, setUserId] = useState<string>('__all__');
  const [locationId, setLocationId] = useState<string>('__all__');
  const [format, setFormat] = useState<'summary' | 'detail'>('summary');
  const [summaryRows, setSummaryRows] = useState<AllCashierUserSummaryRow[]>([]);
  const [detailRows, setDetailRows] = useState<AllCashierUserDetailRow[]>([]);
  const [grandTotals, setGrandTotals] = useState<CashierSummaryPaymentAmounts | null>(null);
  const [totalReceipts, setTotalReceipts] = useState(0);
  const [reportMeta, setReportMeta] = useState<{
    from: string;
    to: string;
    userLabel: string;
    locationLabel: string;
    format: 'summary' | 'detail';
    generatedAt: string;
    generatedBy: string;
  } | null>(null);

  const userOptions = [{ id: '__all__', name: 'All Users' }, ...initialUserOptions];

  const formatRangeLabel = (fromStr: string, toStr: string) => {
    try {
      const f = new Date(fromStr);
      const t = new Date(toStr);
      return `${f.toLocaleString(undefined, { dateStyle: 'short', timeStyle: 'short' })} - ${t.toLocaleString(undefined, { dateStyle: 'short', timeStyle: 'short' })}`;
    } catch {
      return `${fromStr} - ${toStr}`;
    }
  };

  const renderReportMetaCard = (meta: {
    from: string;
    to: string;
    userLabel: string;
    locationLabel: string;
    format: 'summary' | 'detail';
    generatedAt: string;
    generatedBy: string;
  }) => (
    <div className="rounded-md border border-primary/30 bg-primary/5 shadow-sm px-3 py-2.5">
      <div className="mb-2 flex items-center gap-2 border-l-2 border-primary pl-2">
        <p className="text-[11px] font-semibold tracking-wide text-primary">Report Generation Details</p>
      </div>
      <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
        <div className="space-y-0.5 sm:col-span-2">
          <p className="text-[10px] uppercase tracking-wide text-muted-foreground">Filters</p>
          <p className="text-[11px] leading-tight font-medium">
            User: {meta.userLabel} | Branch: {meta.locationLabel} | Range: {formatRangeLabel(meta.from, meta.to)} | Format:{' '}
            {meta.format === 'detail' ? 'Detail' : 'Summary'}
          </p>
        </div>
        <div className="space-y-0.5">
          <p className="text-[10px] uppercase tracking-wide text-muted-foreground">Generated by</p>
          <p className="text-[11px] font-semibold leading-tight">{meta.generatedBy}</p>
        </div>
        <div className="space-y-0.5">
          <p className="text-[10px] uppercase tracking-wide text-muted-foreground">Generated at</p>
          <p className="text-[11px] font-semibold leading-tight">{meta.generatedAt}</p>
        </div>
      </div>
    </div>
  );

  const runSearch = async () => {
    if (!fromDateTime || !toDateTime) {
      toast({ variant: 'destructive', title: 'Validation Error', description: 'Please select from/to date & time' });
      return;
    }
    setLoading(true);
    try {
      const res = await getAllCashierSummaryDetailReportData({
        userId,
        locationId,
        dateFrom: fromDateTime,
        dateTo: toDateTime,
        format,
      });
      if (!res.success) {
        toast({ variant: 'destructive', title: 'Error', description: res.message || 'Failed to load report' });
        setSummaryRows([]);
        setDetailRows([]);
        setGrandTotals(null);
        setTotalReceipts(0);
        setReportMeta(null);
        return;
      }
      setSummaryRows(res.summaryRows);
      setDetailRows(res.detailRows);
      setGrandTotals(res.grandTotals);
      setTotalReceipts(res.totalReceipts);
      setReportMeta({
        from: fromDateTime,
        to: toDateTime,
        userLabel: userOptions.find((u) => u.id === userId)?.name ?? 'All Users',
        locationLabel: initialLocationOptions.find((l) => l.id === locationId)?.name ?? 'All Branches',
        format,
        generatedAt: new Date().toLocaleString(),
        generatedBy: currentUserName,
      });
    } catch (error: unknown) {
      const msg = error instanceof Error ? error.message : 'Failed to load report';
      toast({ variant: 'destructive', title: 'Error', description: msg });
    } finally {
      setLoading(false);
    }
  };

  const downloadCsv = () => {
    const lines: string[] = [];
    if (format === 'summary') {
      lines.push(['User', 'Receipt Count', ...PAYMENT_COLUMNS.map((c) => c.label)].join(','));
      for (const r of summaryRows) {
        lines.push(
          [r.userName, String(r.receiptCount), ...PAYMENT_COLUMNS.map((c) => String((Number(r[c.key]) || 0) / 100))]
            .map((x) => `"${String(x).replace(/"/g, '""')}"`)
            .join(',')
        );
      }
    } else {
      lines.push(['User', 'Section', 'Receipt Count', ...PAYMENT_COLUMNS.map((c) => c.label)].join(','));
      for (const u of detailRows) {
        for (const s of u.sections) {
          lines.push(
            [u.userName, s.title, String(s.receiptCount), ...PAYMENT_COLUMNS.map((c) => String((Number(s.totals[c.key]) || 0) / 100))]
              .map((x) => `"${String(x).replace(/"/g, '""')}"`)
              .join(',')
          );
        }
      }
    }
    const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `all-cashier-summary-detail-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full py-2 space-y-3">
      <Card>
        <CardHeader className="pb-2">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
            <div>
              <CardTitle className="text-xl font-bold">All Cashier Summary and Detail Report</CardTitle>
              <CardDescription className="text-xs mt-0.5">
                Summary aggregates receipts by cashier. Detail shows section-wise totals per cashier.
              </CardDescription>
            </div>
            <div className="flex gap-2 no-print">
              <Button variant="outline" size="sm" onClick={() => window.print()} className="gap-2"><Printer />Print</Button>
              <Button variant="outline" size="sm" onClick={downloadCsv} className="gap-2"><Download />Download CSV</Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-wrap items-end gap-4 no-print">
            <DateTimeRangePicker
              label="Date & time range"
              from={fromDateTime}
              to={toDateTime}
              onChange={({ from, to }) => {
                setFromDateTime(from ?? '');
                setToDateTime(to ?? '');
              }}
            />
            <div>
              <label className="text-sm font-semibold mb-2 block">Branch</label>
              <Select value={locationId} onValueChange={setLocationId}>
                <SelectTrigger className="w-[200px]"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {initialLocationOptions.map((opt) => (
                    <SelectItem key={opt.id} value={opt.id}>{opt.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <label className="text-sm font-semibold mb-2 block">Select User</label>
              <div className="w-[200px]">
                <SearchableUserSelect
                  options={userOptions}
                  value={userId}
                  onChange={setUserId}
                  label="user"
                  placeholder="Select user"
                />
              </div>
            </div>
            <div>
              <label className="text-sm font-semibold mb-2 block">Format</label>
              <Select value={format} onValueChange={(v) => setFormat(v as 'summary' | 'detail')}>
                <SelectTrigger className="w-[140px]"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="summary">Summary</SelectItem>
                  <SelectItem value="detail">Detail</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button size="sm" onClick={runSearch} disabled={loading} className="h-10 gap-2">
              <SearchIcon className="h-4 w-4" />Search
            </Button>
          </div>
        </CardContent>
      </Card>

      {!reportMeta && (
        <Card className="border-dashed">
          <CardContent className="py-8">
            <p className="text-sm font-medium text-muted-foreground">Search to view report details.</p>
          </CardContent>
        </Card>
      )}

      {reportMeta && (
        <Card className="bg-muted/20">
          <CardHeader className="py-2">
            <CardTitle className="text-base">All Cashier Summary and Detail Report</CardTitle>
            <CardDescription className="text-xs mt-0.5">
              All-cashier report with summary/detail modes for the selected filters.
            </CardDescription>
            {renderReportMetaCard(reportMeta)}
          </CardHeader>
          <CardContent className="space-y-3 py-2">
            {loading ? (
              <div className="text-center py-8">Loading...</div>
            ) : format === 'summary' ? (
              <div className="rounded-md border overflow-x-auto">
                <Table className="text-[11px] [&_th]:px-1.5 [&_td]:px-1.5 [&_th]:border-r [&_th:last-child]:border-r-0 [&_td]:border-r [&_td:last-child]:border-r-0">
                  <TableHeader>
                    <TableRow className="border-b">
                      <TableHead className="w-10 text-right">No.</TableHead>
                      <TableHead className="pr-0">User</TableHead>
                      <TableHead className="text-right">Receipts</TableHead>
                      {PAYMENT_COLUMNS.map((c) => (
                        <TableHead key={c.key} className="text-right tabular-nums">{c.label}</TableHead>
                      ))}
                      <TableHead className="text-center">Handover Date</TableHead>
                      <TableHead className="text-center">Checked By</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {summaryRows.map((r, i) => (
                      <TableRow key={r.userId} className="border-b border-border/50">
                        <TableCell className="text-center tabular-nums">{i + 1}</TableCell>
                        <TableCell className="pr-0">{r.userName}</TableCell>
                        <TableCell className="text-right tabular-nums">{r.receiptCount}</TableCell>
                        {PAYMENT_COLUMNS.map((c) => (
                          <TableCell key={c.key} className="text-right tabular-nums">{formatAmount(r[c.key])}</TableCell>
                        ))}
                        <TableCell className="text-center">
                          <div
                            className="min-h-10 border-b-2 border-dotted border-foreground/45 mx-auto block w-[130px]"
                            aria-hidden
                          />
                        </TableCell>
                        <TableCell className="text-center">
                          <div
                            className="min-h-10 border-b-2 border-dotted border-foreground/45 mx-auto block w-[130px]"
                            aria-hidden
                          />
                        </TableCell>
                      </TableRow>
                    ))}
                    {grandTotals && (
                      <TableRow className="font-medium bg-muted/50">
                        <TableCell colSpan={3} className="text-left">Total</TableCell>
                        {PAYMENT_COLUMNS.map((c) => (
                          <TableCell key={c.key} className="text-right tabular-nums">{formatAmount(grandTotals[c.key])}</TableCell>
                        ))}
                        <TableCell />
                        <TableCell />
                      </TableRow>
                    )}
                  </TableBody>
                </Table>
              </div>
            ) : (
              <div className="space-y-3">
                {detailRows.map((u, idx) => (
                  <div key={u.userId} className="rounded-md border overflow-x-auto">
                    <Table className="text-[11px] [&_th]:px-1.5 [&_td]:px-1.5 [&_th]:border-r [&_td]:border-r">
                      <TableHeader>
                        <TableRow className="border-b">
                          <TableHead className="w-10 text-right">No.</TableHead>
                          <TableHead className="pr-0">User</TableHead>
                          <TableHead>Section</TableHead>
                          <TableHead className="text-right">Receipts</TableHead>
                          {PAYMENT_COLUMNS.map((c) => (
                            <TableHead key={c.key} className="text-right tabular-nums">{c.label}</TableHead>
                          ))}
                          <TableHead className="text-center">Handover Date</TableHead>
                          <TableHead className="text-center">Checked By</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {u.sections.map((s, i) => (
                          <TableRow key={`${u.userId}-${s.key}`} className="border-b border-border/50">
                            <TableCell className="text-center tabular-nums">{i === 0 ? idx + 1 : ''}</TableCell>
                            <TableCell className="pr-0">{i === 0 ? u.userName : ''}</TableCell>
                            <TableCell>{s.title}</TableCell>
                            <TableCell className="text-right tabular-nums">{s.receiptCount}</TableCell>
                            {PAYMENT_COLUMNS.map((c) => (
                              <TableCell key={c.key} className="text-right tabular-nums">{formatAmount(s.totals[c.key])}</TableCell>
                            ))}
                            {i === 0 && (
                              <>
                                <TableCell
                                  rowSpan={u.sections.length + 1}
                                  className="text-center"
                                >
                                  <div
                                    className="min-h-10 border-b-2 border-dotted border-foreground/45 mx-auto block w-[130px]"
                                    aria-hidden
                                  />
                                </TableCell>
                                <TableCell
                                  rowSpan={u.sections.length + 1}
                                  className="text-center"
                                >
                                  <div
                                    className="min-h-10 border-b-2 border-dotted border-foreground/45 mx-auto block w-[130px]"
                                    aria-hidden
                                  />
                                </TableCell>
                              </>
                            )}
                          </TableRow>
                        ))}
                        <TableRow className="font-medium bg-muted/50">
                          <TableCell colSpan={3}>User Total</TableCell>
                          <TableCell className="text-right tabular-nums">{u.receiptCount}</TableCell>
                          {PAYMENT_COLUMNS.map((c) => (
                            <TableCell key={c.key} className="text-right tabular-nums">{formatAmount(u.totals[c.key])}</TableCell>
                          ))}
                        </TableRow>
                      </TableBody>
                    </Table>
                  </div>
                ))}
                {grandTotals && (
                  <div className="rounded-md border overflow-x-auto">
                    <Table className="text-[11px] [&_th]:px-1.5 [&_td]:px-1.5 [&_th]:border-r [&_th:last-child]:border-r-0 [&_td]:border-r [&_td:last-child]:border-r-0">
                      <TableHeader>
                        <TableRow className="border-b">
                          <TableHead colSpan={4}>Grand Total</TableHead>
                          {PAYMENT_COLUMNS.map((c) => (
                            <TableHead key={c.key} className="text-right tabular-nums">{c.label}</TableHead>
                          ))}
                          <TableHead />
                          <TableHead />
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        <TableRow className="font-medium bg-muted/50">
                          <TableCell colSpan={4}>Total</TableCell>
                          {PAYMENT_COLUMNS.map((c) => (
                            <TableCell key={c.key} className="text-right tabular-nums">{formatAmount(grandTotals[c.key])}</TableCell>
                          ))}
                          <TableCell />
                          <TableCell />
                        </TableRow>
                      </TableBody>
                    </Table>
                  </div>
                )}
                <div className="rounded-md border border-primary/20 bg-primary/[0.03] px-3 py-2 text-[11px]">
                  <span className="text-muted-foreground">Total receipts in report:</span> <span className="font-semibold">{totalReceipts}</span>
                </div>
                {renderReportMetaCard(reportMeta)}
              </div>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
