'use client';

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { DateTimeRangePicker } from '@/components/common/date-time-range-picker';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/components/hooks/use-toast';
import { FileSpreadsheet, FileText, Loader2, Printer, SearchIcon } from 'lucide-react';
import { getAgencyStatementReportData } from '@/app/actions/reports/agency-statement.report.action';
import type { AgencyStatementReportData } from '@/types/reports/agency-statement';
import { formatLKR } from '@/lib/format-money';
import { formatReportRangeLabel } from '@/lib/format-report-range-label';
import { formatExportFileName } from '@/lib/utils';
import { ReportAgentSelect } from '@/components/common/agent-select';
import { ReportGenerationDetailsCard } from '@/components/common/report-generation-details';
import {
  ReportPrintLayout,
  toBrandedPdfSummaryItems,
} from '@/components/common/report-print';
import type { ReportPrintSummaryItem } from '@/components/common/report-print';
import { AgencyStatementPrintLayout } from './agency-statement-print-layout';
import { downloadAgencyStatementReportPdf } from './agency-statement-pdf';
import { downloadAgencyStatementReportExcel } from './agency-statement-excel';

type Props = {
  agentOptions: Array<{ id: string; name: string }>;
  currentUserName: string;
};

function getDefaultDateTimeRange(): { from: string; to: string } {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  return { from: `${y}-${m}-${d}T00:00`, to: `${y}-${m}-${d}T23:59` };
}

export default function AgencyStatementReportContent({ agentOptions, currentUserName }: Props) {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [loadingExcel, setLoadingExcel] = useState(false);
  const [fromDateTime, setFromDateTime] = useState<string>(() => getDefaultDateTimeRange().from);
  const [toDateTime, setToDateTime] = useState<string>(() => getDefaultDateTimeRange().to);
  const [agencyId, setAgencyId] = useState<string>('');
  const [data, setData] = useState<AgencyStatementReportData | null>(null);
  const [meta, setMeta] = useState<{
    generatedAt: string;
    generatedBy: string;
    from: string;
    to: string;
  } | null>(null);

  const buildSummaryItems = (
    reportData: AgencyStatementReportData,
    reportMeta: { generatedAt: string; generatedBy: string; from: string; to: string }
  ): ReportPrintSummaryItem[] => [
    { label: 'Period', value: formatReportRangeLabel(reportMeta.from, reportMeta.to) },
    { label: 'Agent', value: `${reportData.agencyName} (${reportData.agencyCode})` },
    { label: 'Generated By', value: reportMeta.generatedBy },
    { label: 'Generated At', value: reportMeta.generatedAt },
  ];

  const runSearch = async () => {
    if (!agencyId) {
      toast({ variant: 'destructive', title: 'Validation Error', description: 'Please select at least one agent.' });
      return;
    }
    setLoading(true);
    try {
      const res = await getAgencyStatementReportData({ agencyId, dateFrom: fromDateTime, dateTo: toDateTime });
      if (!res.success || !res.data) {
        toast({ variant: 'destructive', title: 'Error', description: res.message || 'Failed to load statement' });
        setData(null);
        setMeta(null);
        return;
      }
      setData(res.data);
      setMeta({
        generatedAt: new Date().toLocaleString(),
        generatedBy: currentUserName,
        from: fromDateTime,
        to: toDateTime,
      });
    } catch (error: unknown) {
      const msg = error instanceof Error ? error.message : 'Failed to load statement';
      toast({ variant: 'destructive', title: 'Error', description: msg });
    } finally {
      setLoading(false);
    }
  };

  const downloadPdf = async () => {
    if (!data || !meta) {
      toast({ variant: 'destructive', title: 'No data', description: 'Run a search first to download PDF.' });
      return;
    }
    await downloadAgencyStatementReportPdf({
      reportName: 'Agency Statement',
      summaryItems: toBrandedPdfSummaryItems(buildSummaryItems(data, meta)),
      generatedAt: meta.generatedAt,
      data,
      periodFrom: meta.from,
      fileName: `${formatExportFileName('agency-statement')}.pdf`,
    });
  };

  const downloadExcel = async () => {
    if (!data || !meta) {
      toast({ variant: 'destructive', title: 'No data', description: 'Run a search first to download Excel.' });
      return;
    }
    setLoadingExcel(true);
    try {
      await downloadAgencyStatementReportExcel({
        reportName: 'Agency Statement',
        summaryItems: toBrandedPdfSummaryItems(buildSummaryItems(data, meta)),
        generatedAt: meta.generatedAt,
        data,
        periodFrom: meta.from,
        fileName: `${formatExportFileName('agency-statement')}.xlsx`,
        sheetName: 'Agency Statement',
      });
    } catch (error: unknown) {
      toast({
        variant: 'destructive',
        title: 'Excel export failed',
        description: error instanceof Error ? error.message : 'Unable to generate Excel.',
      });
    } finally {
      setLoadingExcel(false);
    }
  };

  const renderMeta = () =>
    data && meta ? (
      <ReportGenerationDetailsCard
        items={[
          {
            label: 'Filters',
            value: (
              <>
                Agent: {data.agencyName} ({data.agencyCode}) | Range:{' '}
                {formatReportRangeLabel(meta.from, meta.to)}
              </>
            ),
            smColSpan: 2,
          },
          { label: 'Generated by', value: <span className="font-semibold">{meta.generatedBy}</span> },
          { label: 'Generated at', value: <span className="font-semibold">{meta.generatedAt}</span> },
        ]}
      />
    ) : null;

  return (
    <div className="w-full py-2 space-y-3 agency-statement-report-root">
      <Card className="print:hidden">
        <CardHeader className="pb-2">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
            <div>
              <CardTitle className="text-xl font-bold">Agency Statement</CardTitle>
              <CardDescription className="text-xs mt-0.5">
                Statement by selected agent with opening and closing balances.
              </CardDescription>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={() => window.print()} className="gap-2"><Printer />Print</Button>
              <Button variant="outline" size="sm" onClick={downloadPdf} className="gap-2"><FileText />PDF</Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => {
                  void downloadExcel();
                }}
                disabled={loadingExcel}
                className="gap-2"
              >
                {loadingExcel ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <FileSpreadsheet className="h-4 w-4" />
                )}
                Excel
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-wrap items-end gap-4">
            <DateTimeRangePicker
              label="Date & time range"
              from={fromDateTime}
              to={toDateTime}
              onChange={({ from, to }) => {
                setFromDateTime(from ?? '');
                setToDateTime(to ?? '');
              }}
            />
            <ReportAgentSelect
              label="Select Agent"
              agentOptions={agentOptions}
              value={agencyId}
              onChange={(v) => setAgencyId(v ?? '')}
              includeAllAgents={false}
            />
            <Button size="sm" onClick={runSearch} disabled={loading} className="h-10 gap-2">
              <SearchIcon className="h-4 w-4" />Search
            </Button>
          </div>
        </CardContent>
      </Card>

      {!data && (
        <Card className="border-dashed print:hidden">
          <CardContent className="py-8">
            <p className="text-sm font-medium text-muted-foreground">Select an agent and click Search to generate statement.</p>
          </CardContent>
        </Card>
      )}

      {data && meta && (
        <Card className="bg-muted/20 print:shadow-none print:border-0 print:bg-white">
          <CardHeader className="py-2 print:hidden">
            <CardTitle className="text-base">Agency Statement</CardTitle>
            <CardDescription className="text-xs mt-0.5">
              Opening Balance: {formatLKR(data.openingBalance)} | Closing Balance: {formatLKR(data.closingBalance)}
            </CardDescription>
            {data.message && <div className="rounded-md border border-amber-300 bg-amber-50 px-2 py-1 text-[11px] text-amber-800">{data.message}</div>}
            {renderMeta()}
          </CardHeader>
          <CardContent className="space-y-3 py-2">
            <ReportPrintLayout
              reportName="Agency Statement"
              pageSize="A4 portrait"
              generatedAt={meta.generatedAt}
              summaryItems={buildSummaryItems(data, meta)}
            >
              {loading ? (
                <div className="text-center py-8 print:hidden">Loading...</div>
              ) : (
                <>
                  <div className="rounded-md border overflow-x-auto print:hidden">
                    <Table className="text-[11px] [&_th]:px-1.5 [&_td]:px-1.5 [&_th]:border-r [&_th:last-child]:border-r-0 [&_td]:border-r [&_td:last-child]:border-r-0">
                      <TableHeader>
                        <TableRow className="border-b">
                          <TableHead className="w-10 text-right">No.</TableHead>
                          <TableHead>Date</TableHead>
                          <TableHead>Particulars</TableHead>
                          <TableHead>Appointment Date/Time</TableHead>
                          <TableHead>Receipt No</TableHead>
                          <TableHead className="text-right">Doc Fee</TableHead>
                          <TableHead className="text-right">Hos Fee</TableHead>
                          <TableHead className="text-right">Discount</TableHead>
                          <TableHead className="text-right">Amount</TableHead>
                          <TableHead className="text-right">Balance</TableHead>
                          <TableHead>Comments</TableHead>
                          <TableHead>Transaction Create By</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        <TableRow className="border-b border-border/50">
                          <TableCell />
                          <TableCell>{new Date(meta.from).toLocaleString()}</TableCell>
                          <TableCell>Balance as of period start</TableCell>
                          <TableCell />
                          <TableCell />
                          <TableCell className="text-right">-</TableCell>
                          <TableCell className="text-right">-</TableCell>
                          <TableCell className="text-right">0.00</TableCell>
                          <TableCell className="text-right">{formatLKR(0)}</TableCell>
                          <TableCell className="text-right tabular-nums">{formatLKR(data.openingBalance)}</TableCell>
                          <TableCell />
                          <TableCell />
                        </TableRow>
                        {data.rows.map((r) => (
                          <TableRow key={`${r.no}-${r.receiptNo}`} className="border-b border-border/50">
                            <TableCell className="text-center tabular-nums">{r.no}</TableCell>
                            <TableCell>{new Date(r.date).toLocaleString()}</TableCell>
                            <TableCell>{r.particulars}</TableCell>
                            <TableCell>{r.appointmentDateTime ?? '-'}</TableCell>
                            <TableCell>{r.receiptNo}</TableCell>
                            <TableCell className="text-right tabular-nums">{formatLKR(r.docFee)}</TableCell>
                            <TableCell className="text-right tabular-nums">{formatLKR(r.hosFee)}</TableCell>
                            <TableCell className="text-right tabular-nums">{formatLKR(r.discount)}</TableCell>
                            <TableCell className="text-right tabular-nums">{formatLKR(r.amount)}</TableCell>
                            <TableCell className="text-right tabular-nums">{formatLKR(r.runningBalance)}</TableCell>
                            <TableCell>{r.comments || '-'}</TableCell>
                            <TableCell>{r.createdBy}</TableCell>
                          </TableRow>
                        ))}
                        <TableRow className="rpt-print-total font-medium bg-muted/50">
                          <TableCell colSpan={9}>Closing Balance</TableCell>
                          <TableCell className="text-right tabular-nums">{formatLKR(data.closingBalance)}</TableCell>
                          <TableCell colSpan={2} />
                        </TableRow>
                      </TableBody>
                    </Table>
                  </div>
                  <AgencyStatementPrintLayout
                    data={data}
                    periodFrom={meta.from}
                  />
                  <div className="print:hidden">{renderMeta()}</div>
                </>
              )}
            </ReportPrintLayout>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
