'use client';

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { DateTimeRangePicker } from '@/components/common/date-time-range-picker';
import { Combobox } from '@/components/common/combobox';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/components/hooks/use-toast';
import { Download, Printer, SearchIcon } from 'lucide-react';
import { getAgencyStatementReportData } from '@/app/actions/reports/agency-statement.report.action';
import type { AgencyStatementReportData } from '@/types/reports/agency-statement';
import { formatLKR } from '@/lib/format-money';

type Props = {
  agentOptions: Array<{ id: string; name: string }>;
  currentUserName: string;
};

function getDefaultDateTimeRange(): { from: string; to: string } {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  return { from: `${y}-${m}-${d}T00:00`, to: `${y}-${m}-${d}T23:59` };
}

export default function AgencyStatementReportContent({ agentOptions, currentUserName }: Props) {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [fromDateTime, setFromDateTime] = useState<string>(() => getDefaultDateTimeRange().from);
  const [toDateTime, setToDateTime] = useState<string>(() => getDefaultDateTimeRange().to);
  const [agencyId, setAgencyId] = useState<string>('');
  const [data, setData] = useState<AgencyStatementReportData | null>(null);
  const [meta, setMeta] = useState<{ generatedAt: string; generatedBy: string } | null>(null);

  const runSearch = async () => {
    if (!agencyId) {
      toast({ variant: 'destructive', title: 'Validation Error', description: 'Please select at least one agent.' });
      return;
    }
    setLoading(true);
    try {
      const res = await getAgencyStatementReportData({ agencyId, dateFrom: fromDateTime, dateTo: toDateTime });
      if (!res.success || !res.data) {
        toast({ variant: 'destructive', title: 'Error', description: res.message || 'Failed to load statement' });
        setData(null);
        setMeta(null);
        return;
      }
      setData(res.data);
      setMeta({ generatedAt: new Date().toLocaleString(), generatedBy: currentUserName });
    } catch (error: unknown) {
      const msg = error instanceof Error ? error.message : 'Failed to load statement';
      toast({ variant: 'destructive', title: 'Error', description: msg });
    } finally {
      setLoading(false);
    }
  };

  const downloadCsv = () => {
    if (!data) return;
    const lines = [
      ['No.', 'Date', 'Particulars', 'Appointment Date/Time', 'Receipt No', 'Doc Fee', 'Hos Fee', 'Discount', 'Amount', 'Balance', 'Comments', 'Transaction Create By'].join(','),
      ...data.rows.map((r) =>
        [
          r.no,
          new Date(r.date).toLocaleString(),
          r.particulars,
          r.appointmentDateTime ?? '',
          r.receiptNo,
          r.docFee.toFixed(2),
          r.hosFee.toFixed(2),
          r.discount.toFixed(2),
          r.amount.toFixed(2),
          r.runningBalance.toFixed(2),
          r.comments,
          r.createdBy,
        ]
          .map((v) => `"${String(v).replace(/"/g, '""')}"`)
          .join(',')
      ),
      '',
      `"Opening Balance",,,,,,,,,"${data.openingBalance.toFixed(2)}",,`,
      `"Closing Balance",,,,,,,,,"${data.closingBalance.toFixed(2)}",,`,
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `agency-statement-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const renderMeta = () =>
    data && meta ? (
      <div className="rounded-md border border-primary/30 bg-primary/5 shadow-sm px-3 py-2.5">
        <div className="mb-2 flex items-center gap-2 border-l-2 border-primary pl-2">
          <p className="text-[11px] font-semibold tracking-wide text-primary">Report Generation Details</p>
        </div>
        <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
          <div className="space-y-0.5 sm:col-span-2">
            <p className="text-[10px] uppercase tracking-wide text-muted-foreground">Filters</p>
            <p className="text-[11px] leading-tight font-medium">
              Agent: {data.agencyName} ({data.agencyCode}) | Range: {new Date(fromDateTime).toLocaleString()} - {new Date(toDateTime).toLocaleString()}
            </p>
          </div>
          <div className="space-y-0.5">
            <p className="text-[10px] uppercase tracking-wide text-muted-foreground">Generated by</p>
            <p className="text-[11px] font-semibold leading-tight">{meta.generatedBy}</p>
          </div>
          <div className="space-y-0.5">
            <p className="text-[10px] uppercase tracking-wide text-muted-foreground">Generated at</p>
            <p className="text-[11px] font-semibold leading-tight">{meta.generatedAt}</p>
          </div>
        </div>
      </div>
    ) : null;

  return (
    <div className="w-full py-2 space-y-3">
      <Card>
        <CardHeader className="pb-2">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
            <div>
              <CardTitle className="text-xl font-bold">Agency Statement</CardTitle>
              <CardDescription className="text-xs mt-0.5">
                Statement by selected agent with opening and closing balances.
              </CardDescription>
            </div>
            <div className="flex gap-2 no-print">
              <Button variant="outline" size="sm" onClick={() => window.print()} className="gap-2"><Printer />Print</Button>
              <Button variant="outline" size="sm" onClick={downloadCsv} className="gap-2"><Download />Download CSV</Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-wrap items-end gap-4 no-print">
            <DateTimeRangePicker
              label="Date & time range"
              from={fromDateTime}
              to={toDateTime}
              onChange={({ from, to }) => {
                setFromDateTime(from ?? '');
                setToDateTime(to ?? '');
              }}
            />
            <Combobox
              label="Select Agent"
              options={agentOptions}
              value={agencyId || undefined}
              onChange={(v) => setAgencyId(v ?? '')}
            />
            <Button size="sm" onClick={runSearch} disabled={loading} className="h-10 gap-2">
              <SearchIcon className="h-4 w-4" />Search
            </Button>
          </div>
        </CardContent>
      </Card>

      {!data && (
        <Card className="border-dashed">
          <CardContent className="py-8">
            <p className="text-sm font-medium text-muted-foreground">Select an agent and click Search to generate statement.</p>
          </CardContent>
        </Card>
      )}

      {data && (
        <Card className="bg-muted/20">
          <CardHeader className="py-2">
            <CardTitle className="text-base">Agency Statement</CardTitle>
            <CardDescription className="text-xs mt-0.5">
              Opening Balance: {formatLKR(data.openingBalance)} | Closing Balance: {formatLKR(data.closingBalance)}
            </CardDescription>
            {data.message && <div className="rounded-md border border-amber-300 bg-amber-50 px-2 py-1 text-[11px] text-amber-800">{data.message}</div>}
            {renderMeta()}
          </CardHeader>
          <CardContent className="space-y-3 py-2">
            {loading ? (
              <div className="text-center py-8">Loading...</div>
            ) : (
              <>
                <div className="rounded-md border overflow-x-auto">
                  <Table className="text-[11px] [&_th]:px-1.5 [&_td]:px-1.5 [&_th]:border-r [&_th:last-child]:border-r-0 [&_td]:border-r [&_td:last-child]:border-r-0">
                    <TableHeader>
                      <TableRow className="border-b">
                        <TableHead className="w-10 text-right">No.</TableHead>
                        <TableHead>Date</TableHead>
                        <TableHead>Particulars</TableHead>
                        <TableHead>Appointment Date/Time</TableHead>
                        <TableHead>Receipt No</TableHead>
                        <TableHead className="text-right">Doc Fee</TableHead>
                        <TableHead className="text-right">Hos Fee</TableHead>
                        <TableHead className="text-right">Discount</TableHead>
                        <TableHead className="text-right">Amount</TableHead>
                        <TableHead className="text-right">Balance</TableHead>
                        <TableHead>Comments</TableHead>
                        <TableHead>Transaction Create By</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      <TableRow className="border-b border-border/50">
                        <TableCell />
                        <TableCell>{new Date(fromDateTime).toLocaleString()}</TableCell>
                        <TableCell>Balance as of period start</TableCell>
                        <TableCell />
                        <TableCell />
                        <TableCell className="text-right">-</TableCell>
                        <TableCell className="text-right">-</TableCell>
                        <TableCell className="text-right">0.00</TableCell>
                        <TableCell className="text-right">{formatLKR(0)}</TableCell>
                        <TableCell className="text-right tabular-nums">{formatLKR(data.openingBalance)}</TableCell>
                        <TableCell />
                        <TableCell />
                      </TableRow>
                      {data.rows.map((r) => (
                        <TableRow key={`${r.no}-${r.receiptNo}`} className="border-b border-border/50">
                          <TableCell className="text-center tabular-nums">{r.no}</TableCell>
                          <TableCell>{new Date(r.date).toLocaleString()}</TableCell>
                          <TableCell>{r.particulars}</TableCell>
                          <TableCell>{r.appointmentDateTime ?? '-'}</TableCell>
                          <TableCell>{r.receiptNo}</TableCell>
                          <TableCell className="text-right tabular-nums">{formatLKR(r.docFee)}</TableCell>
                          <TableCell className="text-right tabular-nums">{formatLKR(r.hosFee)}</TableCell>
                          <TableCell className="text-right tabular-nums">{formatLKR(r.discount)}</TableCell>
                          <TableCell className="text-right tabular-nums">{formatLKR(r.amount)}</TableCell>
                          <TableCell className="text-right tabular-nums">{formatLKR(r.runningBalance)}</TableCell>
                          <TableCell>{r.comments || '-'}</TableCell>
                          <TableCell>{r.createdBy}</TableCell>
                        </TableRow>
                      ))}
                      <TableRow className="font-medium bg-muted/50">
                        <TableCell colSpan={9}>Closing Balance</TableCell>
                        <TableCell className="text-right tabular-nums">{formatLKR(data.closingBalance)}</TableCell>
                        <TableCell colSpan={2} />
                      </TableRow>
                    </TableBody>
                  </Table>
                </div>
                {renderMeta()}
              </>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
