/**
 * Seed default receipt templates (same logic as scripts/seed-receipt-templates.ts).
 * Used by the CLI script and by the admin seed page.
 * Wipe-and-recreate runs only when SEED_HELPER is enabled in .env.
 * `ensureDefaultReceiptTemplates` upserts missing/outdated defaults without deleting custom templates.
 */

import prisma from "@/lib/prisma"
import {
  RUHUNU_HOSPITAL,
  ruhunuEmailWebLine,
  ruhunuPhoneFaxLine,
} from "@/lib/receipt-template/ruhunu-hospital"
import { isSeedHelperEnabled, SEED_HELPER_DISABLED_MESSAGE } from "./seed-helper-enabled"
import {
  A5_PAPER_HEIGHT_MM,
  A5_PAPER_WIDTH_MM,
  DOT_MATRIX_PAPER_HEIGHT_MM,
  DOT_MATRIX_PAPER_WIDTH_MM,
  RECEIPT_PRINT_VARIANT_DOT_MATRIX,
} from "@/types/receipt-template-db"

const DEFAULT_HEADER = {
  name: "Ruhunu Hospital header",
  content: `{{company_name}}
{{location_address}}

${ruhunuPhoneFaxLine()}
${ruhunuEmailWebLine()}`,
}

const LEDGER_HEADER = {
  name: "Ruhunu ledger header",
  content: `<div class="hospital-name">{{company_name}}</div>
<div class="hospital-address">{{location_address}}</div>
<p class="contact">Tel : {{tel}}</p>
<p class="contact contact-email">Email : {{email}} | Web : {{web}}</p>`,
}

const DEFAULT_FOOTER = {
  name: "Ruhunu Hospital footer",
  content: `<p class="generated">Generated By : {{generated_by}} &nbsp; {{generated_at}}</p>`,
}

const COMPACT_HEADER = {
  name: "Ruhunu compact header",
  content: `{{company_name}} – {{location_address}} | ${ruhunuPhoneFaxLine()} | ${RUHUNU_HOSPITAL.email}`,
}

const COMPACT_FOOTER = {
  name: "Ruhunu compact footer",
  content: `Generated by {{generated_by}} on {{generated_at}}`,
}

/** Sails-style HTML body for graphics-capable dot-matrix (tables, not space-padded text). */
const LEDGER_BODY = `<div class="bill-title">{{title}}</div>
{{status_banner}}
{{info_block}}
{{payment_table}}
<p class="remarks">Remarks : {{remarks}}</p>`

const BOOKING_RECEIPT_BODY = `Invoice - Hospital Bill
{{status_banner}}

Number: {{appointment_no}}
Name: {{patient_name}}
Invoice No: {{bill_no}}
Phone: {{phone}}
Appointment Type: {{booking_method}}
App. Date: {{appointment_date}}
App. Time: {{appointment_time}}
Hospital Fee: {{hospital_fee}}
Discount: {{hospital_fee_discount}}
Total Hospital Fee: {{total_hospital_fee}}
Billed At: {{billed_at}}
Cashier Code: {{cashier_code}}
Invoice Status: {{invoice_status}}
Printed by: {{printed_by}}

Professional Bill
{{status_banner}}

Name: {{patient_name}}
Invoice Ref: {{bill_no}}
Consultant: {{consultant}}
Professional Charges: {{professional_fee}}

Collected for and on behalf of the Doctor*`

const DOCTOR_PAYMENT_BODY = `Consultant Payment {{duplicate_label}}

{{company_name}}
{{location_name}}

Document Status: {{document_status}}
Invoice No: {{invoice_no}}

Consultant: {{consultant_name}}

{{line_items}}

Sub Payable: {{sub_payable}}
WHT: {{wht}}
Net Paid Amount: {{net_paid_amount}}

Total Patient Count: {{total_patient_count}}

Paid To: {{paid_to}}
Paid By: {{paid_by}}
Paid On: {{paid_on}}

Remarks: {{remarks}}
Slip Reference: {{slip_reference}}
Slip Date: {{slip_date}}

Generated By: {{generated_by}}
{{generated_at}}`

const RECEIPT_TYPES: { type: string; label: string; body: string }[] = [
  { type: "ledger", label: "Ledger", body: LEDGER_BODY },
  { type: "agent_receipt", label: "Agent Receipt", body: LEDGER_BODY },
  { type: "expenses_note", label: "Expenses Note", body: LEDGER_BODY },
  { type: "debit_note", label: "Debit Note", body: LEDGER_BODY },
  { type: "doctor_payment", label: "Consultant Payment", body: DOCTOR_PAYMENT_BODY },
  { type: "booking_receipt", label: "Booking Receipt", body: BOOKING_RECEIPT_BODY },
]

export type SeedReceiptTemplatesResult =
  | { success: true; message: string; details: string }
  | { success: false; message: string }

async function findOrCreateHeader(name: string, content: string) {
  const existing = await prisma.receiptHeaderTemplate.findFirst({ where: { name } })
  if (existing) {
    if (existing.content !== content) {
      return prisma.receiptHeaderTemplate.update({
        where: { id: existing.id },
        data: { content },
      })
    }
    return existing
  }
  return prisma.receiptHeaderTemplate.create({ data: { name, content } })
}

async function findOrCreateFooter(name: string, content: string) {
  const existing = await prisma.receiptFooterTemplate.findFirst({ where: { name } })
  if (existing) {
    if (existing.content !== content) {
      return prisma.receiptFooterTemplate.update({
        where: { id: existing.id },
        data: { content },
      })
    }
    return existing
  }
  return prisma.receiptFooterTemplate.create({ data: { name, content } })
}

function templateName(type: string, label: string, variant: "slip_printer" | "custom_size"): string {
  if (variant === "slip_printer") return `${label} – Slip printer`
  if (type === "booking_receipt") return `${label} – Dot matrix`
  return `${label} – A5`
}

function paperForVariant(
  type: string,
  variant: "slip_printer" | "custom_size"
): {
  paperWidthMm: number
  paperHeightMm: number | null
} {
  if (variant === "slip_printer") return { paperWidthMm: 80, paperHeightMm: null }
  if (type === "booking_receipt") {
    return { paperWidthMm: DOT_MATRIX_PAPER_WIDTH_MM, paperHeightMm: DOT_MATRIX_PAPER_HEIGHT_MM }
  }
  return { paperWidthMm: A5_PAPER_WIDTH_MM, paperHeightMm: A5_PAPER_HEIGHT_MM }
}

/**
 * Upsert default templates (headers, footers, slip + dot-matrix) without deleting existing rows.
 * Safe to run on an environment that already has templates.
 */
export async function ensureDefaultReceiptTemplates(): Promise<SeedReceiptTemplatesResult> {
  try {
    const lines: string[] = []
    const defaultHeader = await findOrCreateHeader(DEFAULT_HEADER.name, DEFAULT_HEADER.content)
    const ledgerHeader = await findOrCreateHeader(LEDGER_HEADER.name, LEDGER_HEADER.content)
    const compactHeader = await findOrCreateHeader(COMPACT_HEADER.name, COMPACT_HEADER.content)
    const defaultFooter = await findOrCreateFooter(DEFAULT_FOOTER.name, DEFAULT_FOOTER.content)
    const compactFooter = await findOrCreateFooter(COMPACT_FOOTER.name, COMPACT_FOOTER.content)
    lines.push(`Headers ready: ${defaultHeader.name}, ${ledgerHeader.name}, ${compactHeader.name}.`)
    lines.push(`Footers ready: ${defaultFooter.name}, ${compactFooter.name}.`)

    let created = 0
    let updated = 0
    for (const { type, label, body } of RECEIPT_TYPES) {
      const headerId = type === "booking_receipt" ? defaultHeader.id : ledgerHeader.id
      for (const variant of ["slip_printer", RECEIPT_PRINT_VARIANT_DOT_MATRIX] as const) {
        const name = templateName(type, label, variant)
        const paper = paperForVariant(type, variant)
        const existing = await prisma.receiptTemplate.findFirst({
          where: { type, variant },
          orderBy: { updatedAt: "desc" },
        })
        const data = {
          name,
          type,
          variant,
          headerTemplateId: headerId,
          footerTemplateId: defaultFooter.id,
          bodyContent: body,
          paperWidthMm: paper.paperWidthMm,
          paperHeightMm: paper.paperHeightMm,
          status: 1,
        }
        if (!existing) {
          await prisma.receiptTemplate.create({ data })
          created++
        } else {
          await prisma.receiptTemplate.update({
            where: { id: existing.id },
            data,
          })
          updated++
        }
      }
    }
    lines.push(`Upserted ${created + updated} receipt template(s) (${created} created, ${updated} updated).`)
    return {
      success: true,
      message: "Receipt templates seeded.",
      details: lines.join("\n"),
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    return { success: false, message: `Seed failed: ${message}` }
  }
}

export async function runSeedReceiptTemplates(): Promise<SeedReceiptTemplatesResult> {
  if (!isSeedHelperEnabled()) {
    return { success: false, message: SEED_HELPER_DISABLED_MESSAGE }
  }
  try {
    const lines: string[] = []

    const deletedMain = await prisma.receiptTemplate.deleteMany({})
    const deletedHeaders = await prisma.receiptHeaderTemplate.deleteMany({})
    const deletedFooters = await prisma.receiptFooterTemplate.deleteMany({})
    lines.push(`Removed ${deletedMain.count} template(s), ${deletedHeaders.count} header(s), ${deletedFooters.count} footer(s).`)

    const ensured = await ensureDefaultReceiptTemplates()
    if (!ensured.success) return ensured
    lines.push(ensured.details)

    return {
      success: true,
      message: "Receipt templates seeded successfully.",
      details: lines.join("\n"),
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    return { success: false, message: `Seed failed: ${message}` }
  }
}
