/**
 * Seed default receipt templates (same logic as scripts/seed-receipt-templates.ts).
 * Used by the CLI script and by the admin seed page.
 * Runs only when SEED_HELPER is enabled in .env.
 */

import prisma from "@/lib/prisma"
import { isSeedHelperEnabled, SEED_HELPER_DISABLED_MESSAGE } from "./seed-helper-enabled"

const DEFAULT_HEADER = {
  name: "Default branch header",
  content: `{{company_name}}
{{location_name}}

Tel: {{tel}}
Email: {{email}} | Web: {{web}}`,
}

const DEFAULT_FOOTER = {
  name: "Default footer",
  content: `Generated By: {{generated_by}}
{{generated_at}}`,
}

const COMPACT_HEADER = {
  name: "Compact header",
  content: `{{company_name}} – {{location_name}} | Tel: {{tel}} | {{email}}`,
}

const COMPACT_FOOTER = {
  name: "Compact footer",
  content: `Generated by {{generated_by}} on {{generated_at}}`,
}

const LEDGER_BODY = `{{title}}

Date/Time: {{date_time}}

Receipt No: {{receipt_no}}
Branch: {{branch_name}}
Transaction Type: {{transaction_type}}
Amount (Rs): {{amount}}

Comment: {{comment}}
Remarks: {{remarks}}

Payment: {{payment_method}}
Agency: {{agency_name}}
Bank: {{bank}}
Card (last 4): {{card_reference}}
Slip reference: {{slip_reference}}
Slip date: {{slip_date}}`

const DOCTOR_PAYMENT_BODY = `Consultant Payment {{duplicate_label}}

{{company_name}}
{{location_name}}

Document Status: {{document_status}}
Invoice No: {{invoice_no}}

Consultant: {{consultant_name}}

{{line_items}}

Sub Payable: {{sub_payable}}
WHT: {{wht}}
Net Paid Amount: {{net_paid_amount}}

Total Patient Count: {{total_patient_count}}

Paid To: {{paid_to}}
Paid By: {{paid_by}}
Paid On: {{paid_on}}

Remarks: {{remarks}}
Slip Reference: {{slip_reference}}
Slip Date: {{slip_date}}

Generated By: {{generated_by}}
{{generated_at}}`

export type SeedReceiptTemplatesResult =
  | { success: true; message: string; details: string }
  | { success: false; message: string }

export async function runSeedReceiptTemplates(): Promise<SeedReceiptTemplatesResult> {
  if (!isSeedHelperEnabled()) {
    return { success: false, message: SEED_HELPER_DISABLED_MESSAGE }
  }
  try {
    const lines: string[] = []

    const deletedMain = await prisma.receiptTemplate.deleteMany({})
    const deletedHeaders = await prisma.receiptHeaderTemplate.deleteMany({})
    const deletedFooters = await prisma.receiptFooterTemplate.deleteMany({})
    lines.push(`Removed ${deletedMain.count} template(s), ${deletedHeaders.count} header(s), ${deletedFooters.count} footer(s).`)

    const defaultHeader = await prisma.receiptHeaderTemplate.create({ data: DEFAULT_HEADER })
    const compactHeader = await prisma.receiptHeaderTemplate.create({ data: COMPACT_HEADER })
    const defaultFooter = await prisma.receiptFooterTemplate.create({ data: DEFAULT_FOOTER })
    const compactFooter = await prisma.receiptFooterTemplate.create({ data: COMPACT_FOOTER })
    lines.push(`Created headers: ${defaultHeader.name}, ${compactHeader.name}.`)
    lines.push(`Created footers: ${defaultFooter.name}, ${compactFooter.name}.`)

    const receiptTypes: { type: string; label: string; body: string }[] = [
      { type: "ledger", label: "Ledger", body: LEDGER_BODY },
      { type: "agent_receipt", label: "Agent Receipt", body: LEDGER_BODY },
      { type: "expenses_note", label: "Expenses Note", body: LEDGER_BODY },
      { type: "debit_note", label: "Debit Note", body: LEDGER_BODY },
      { type: "doctor_payment", label: "Consultant Payment", body: DOCTOR_PAYMENT_BODY },
    ]

    let created = 0
    for (const { type, label, body } of receiptTypes) {
      for (const variant of ["slip_printer", "custom_size"] as const) {
        const name =
          variant === "slip_printer" ? `${label} – Slip printer` : `${label} – Custom size`
        await prisma.receiptTemplate.create({
          data: {
            name,
            type,
            variant,
            headerTemplateId: defaultHeader.id,
            footerTemplateId: defaultFooter.id,
            bodyContent: body,
            paperWidthMm: variant === "slip_printer" ? 80 : 210,
            paperHeightMm: variant === "slip_printer" ? null : 297,
            status: 1,
          },
        })
        created++
      }
    }
    lines.push(`Created ${created} receipt templates.`)

    return {
      success: true,
      message: "Receipt templates seeded successfully.",
      details: lines.join("\n"),
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    return { success: false, message: `Seed failed: ${message}` }
  }
}
