'use client';

import React, { Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { DateTimeRangePicker } from '@/components/common/date-time-range-picker';
import { Selector } from '@/components/common/selector';
import { Input } from '@/components/ui/input';
import Loading from '@/app/(dashboard)/loading';
import { ReportTemplate } from '@/app/(dashboard)/report-template';
import { formatLKR } from '@/lib/format-money';
import { formatReportRangeLabel } from '@/lib/format-report-range-label';
import { toBrandedPdfSummaryItems } from '@/components/common/report-print';
import { ChannelReportReceiptWiseColumns } from './columns';
import { ChannelReportReceiptWisePrintLayout } from './channel-report-receipt-wise-print-layout';
import { downloadReceiptReportPdf } from './channel-report-receipt-wise-pdf';
import { downloadReceiptReportExcel } from './channel-report-receipt-wise-excel';
import {
  RECEIPT_REPORT_EXPORT_COLUMNS,
  RECEIPT_REPORT_EXPORT_KEYS,
} from './channel-report-receipt-wise-export-config';
import {
  getChannelReportReceiptWiseData,
  exportChannelReportReceiptWiseData,
} from '@/app/actions/reports/channel-report-receipt-wise.report.action';
import type {
  ChannelReportReceiptWiseContentProps,
  ChannelReportReceiptWiseExportRow,
  ChannelReportReceiptWiseRow,
} from '@/types/reports/channel-report-receipt-wise';
import { RECEIPT_CATEGORY_OPTIONS } from '@/types/reports/channel-report-receipt-wise';

function getDefaultDateTimeRange(): { from: string; to: string } {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  return { from: `${y}-${m}-${d}T00:00`, to: `${y}-${m}-${d}T23:59` };
}

function ChannelReportReceiptWiseContentInner(props: ChannelReportReceiptWiseContentProps) {
  const searchParams = useSearchParams();

  const initialFilterValues = React.useMemo(() => {
    const { from, to } = getDefaultDateTimeRange();
    return { fromDateTime: from, toDateTime: to, receiptCategory: '__all__' };
  }, []);

  const buildQuery = () => ({
    fromDateTime: searchParams.get('fromDateTime') ?? undefined,
    toDateTime: searchParams.get('toDateTime') ?? undefined,
    receiptNo: searchParams.get('receiptNo')?.trim() || undefined,
    receiptCategory: searchParams.get('receiptCategory') ?? undefined,
  });

  const buildSummaryItems = React.useCallback((values: Record<string, string | undefined>) => {
    const from = values.fromDateTime ?? '';
    const to = values.toDateTime ?? '';
    return [
      {
        label: 'Period',
        value: from && to ? formatReportRangeLabel(from, to) : `${from || '—'} to ${to || '—'}`,
        fullWidth: true,
      },
      {
        label: 'Category',
        value:
          RECEIPT_CATEGORY_OPTIONS.find((x) => x.id === (values.receiptCategory ?? '__all__'))
            ?.name ?? 'All Categories',
      },
      { label: 'Receipt No', value: values.receiptNo?.trim() || 'All' },
    ];
  }, []);

  /** Same REPORT SUMMARY fields as Print (filters + Generated By/At + Total Records). */
  const buildExportSummaryItems = React.useCallback(
    (values: Record<string, string | undefined>, rowCount: number, generatedAt: string) =>
      toBrandedPdfSummaryItems([
        ...buildSummaryItems(values),
        { label: 'Generated By', value: props.currentUserName },
        { label: 'Generated At', value: generatedAt },
        { label: 'Total Records', value: String(rowCount) },
      ]),
    [buildSummaryItems, props.currentUserName]
  );

  const handlePdfDownload = React.useCallback(
    async (args: {
      title: string;
      data: ChannelReportReceiptWiseExportRow[];
      columns: string[];
      keys: (keyof ChannelReportReceiptWiseExportRow)[];
      fileName?: string;
    }) => {
      const generatedAt = new Date().toLocaleString();
      await downloadReceiptReportPdf({
        reportName: 'Receipt Report',
        summaryItems: buildExportSummaryItems(buildQuery(), args.data.length, generatedAt),
        generatedAt,
        rows: args.data,
        fileName: args.fileName,
      });
    },
    [buildExportSummaryItems]
  );

  const handleExcelDownload = React.useCallback(
    async (args: {
      title: string;
      data: ChannelReportReceiptWiseExportRow[];
      columns: string[];
      keys: (keyof ChannelReportReceiptWiseExportRow)[];
      fileName?: string;
    }) => {
      const generatedAt = new Date().toLocaleString();
      await downloadReceiptReportExcel({
        reportName: 'Receipt Report',
        summaryItems: buildExportSummaryItems(buildQuery(), args.data.length, generatedAt),
        generatedAt,
        rows: args.data,
        fileName: args.fileName,
        sheetName: (args.title || 'Receipt Report').slice(0, 31),
      });
    },
    [buildExportSummaryItems]
  );

  return (
    <ReportTemplate<ChannelReportReceiptWiseRow, ChannelReportReceiptWiseExportRow>
      title="Receipt Report"
      description="Shows all receipts by created date/time range. Filter by receipt type as needed."
      filterButtonLabel="Search"
      printPageSize="A4 portrait"
      containerClassName="container mx-auto py-3 space-y-4 receipt-report-root"
      renderPrintContent={(rows) => <ChannelReportReceiptWisePrintLayout rows={rows} />}
      customDownloadPdf={handlePdfDownload}
      customDownloadExcel={handleExcelDownload}
      initialFilterValues={initialFilterValues}
      skipFetchWhenNoParams={true}
      initialEmptyMessage="No receipts found. Select filters and click Search."
      emptyMessage="No receipts found for the selected filters."
      generationDetails={{
        generatedBy: props.currentUserName,
        formatFilters: (values) => (
          <>
            <div>
              Range: {values.fromDateTime || '—'} to {values.toDateTime || '—'}
            </div>
            <div>
              Category:{' '}
              {RECEIPT_CATEGORY_OPTIONS.find((x) => x.id === (values.receiptCategory ?? '__all__'))
                ?.name ?? 'All Categories'}
            </div>
            <div>Receipt no: {values.receiptNo?.trim() || 'All'}</div>
          </>
        ),
        formatPrintSummaryItems: (values) => buildSummaryItems(values),
      }}
      filterContent={({ values, setValue }) => (
        <div className="flex flex-wrap gap-4 items-end">
          <DateTimeRangePicker
            label="Date & Time Range"
            from={values.fromDateTime}
            to={values.toDateTime}
            onChange={({ from, to }) => {
              setValue('fromDateTime', from);
              setValue('toDateTime', to);
            }}
          />
          <div className="w-full sm:w-[300px]">
            <Selector
              label="Receipt Category"
              options={RECEIPT_CATEGORY_OPTIONS}
              value={values.receiptCategory ?? '__all__'}
              onChange={(v) => setValue('receiptCategory', v)}
            />
          </div>
          <div className="w-full sm:w-[260px]">
            <label className="text-sm text-black font-semibold mb-2 block">Receipt No</label>
            <Input
              placeholder="Enter receipt no"
              value={values.receiptNo ?? ''}
              onChange={(e) => setValue('receiptNo', e.target.value || undefined)}
            />
          </div>
        </div>
      )}
      fetchData={async (params) =>
        getChannelReportReceiptWiseData({
          fromDateTime: params.get('fromDateTime') ?? undefined,
          toDateTime: params.get('toDateTime') ?? undefined,
          receiptNo: params.get('receiptNo')?.trim() || undefined,
          receiptCategory: params.get('receiptCategory') ?? undefined,
        })
      }
      exportData={async () => exportChannelReportReceiptWiseData(buildQuery())}
      columns={ChannelReportReceiptWiseColumns}
      exportColumns={RECEIPT_REPORT_EXPORT_COLUMNS}
      exportKeys={RECEIPT_REPORT_EXPORT_KEYS as (keyof ChannelReportReceiptWiseExportRow)[]}
      exportTitle="Receipt Report"
      exportFileName="receipt-report"
      getRowId={(row) => row.id}
      totalColumnIds={['receiptAmount', 'whdAmount', 'netAmount']}
      formatTotalValue={(_columnId, sum) => formatLKR(sum)}
      tableClassName="text-[11px] [&_th]:px-1.5 [&_td]:px-1.5 [&_th]:border-r [&_th:last-child]:border-r-0 [&_td]:border-r [&_td:last-child]:border-r-0"
    />
  );
}

export default function ChannelReportReceiptWiseContent(props: ChannelReportReceiptWiseContentProps) {
  return (
    <Suspense fallback={<Loading />}>
      <ChannelReportReceiptWiseContentInner {...props} />
    </Suspense>
  );
}
