/**
 * Seed default receipt templates for all Ledger document types:
 * Ledger (general), Agent Receipt, Expenses Note, Debit Note.
 * 1. Removes ALL receipt templates (main, then header, then footer).
 * 2. Creates default header and footer templates.
 * 3. Creates receipt templates for each type (ledger, agent_receipt, expenses_note, debit_note)
 *    with both variants (slip_printer, custom_size).
 *
 * Run: npx tsx scripts/seed-receipt-templates.ts
 * Or:  npm run seed:receipt-templates
 */

import "dotenv/config"
import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

// --- Header: company name, location, contact (placeholders) ---
const DEFAULT_HEADER = {
  name: "Default branch header",
  content: `{{company_name}}
{{location_name}}

Tel: {{tel}}
Email: {{email}} | Web: {{web}}`,
}

// --- Footer: generated by, date (placeholders) ---
const DEFAULT_FOOTER = {
  name: "Default footer",
  content: `Generated By: {{generated_by}}
{{generated_at}}`,
}

// --- Optional second header: compact single-line style ---
const COMPACT_HEADER = {
  name: "Compact header",
  content: `{{company_name}} – {{location_name}} | Tel: {{tel}} | {{email}}`,
}

// --- Optional second footer: single line ---
const COMPACT_FOOTER = {
  name: "Compact footer",
  content: `Generated by {{generated_by}} on {{generated_at}}`,
}

const LEDGER_BODY = `{{title}}

Date/Time: {{date_time}}

Receipt No: {{receipt_no}}
Branch: {{branch_name}}
Transaction Type: {{transaction_type}}
Amount (Rs): {{amount}}

Comment: {{comment}}
Remarks: {{remarks}}

Payment: {{payment_method}}
Agency: {{agency_name}}
Bank: {{bank}}
Card (last 4): {{card_reference}}
Slip reference: {{slip_reference}}`

async function main() {
  console.log("Seeding receipt templates (remove all, then re-add)...\n")

  // --- 1. Remove all receipt templates (main first: they reference header/footer) ---
  console.log("Removing all receipt templates...")
  const deletedMain = await prisma.receiptTemplate.deleteMany({})
  console.log("  Deleted", deletedMain.count, "receipt template(s).")

  const deletedHeaders = await prisma.receiptHeaderTemplate.deleteMany({})
  console.log("  Deleted", deletedHeaders.count, "header template(s).")

  const deletedFooters = await prisma.receiptFooterTemplate.deleteMany({})
  console.log("  Deleted", deletedFooters.count, "footer template(s).")
  console.log("")

  // --- 2. Create header templates ---
  console.log("Creating header templates...")
  const defaultHeader = await prisma.receiptHeaderTemplate.create({
    data: DEFAULT_HEADER,
  })
  console.log("  Created:", defaultHeader.name)

  const compactHeader = await prisma.receiptHeaderTemplate.create({
    data: COMPACT_HEADER,
  })
  console.log("  Created:", compactHeader.name)
  console.log("")

  // --- 3. Create footer templates ---
  console.log("Creating footer templates...")
  const defaultFooter = await prisma.receiptFooterTemplate.create({
    data: DEFAULT_FOOTER,
  })
  console.log("  Created:", defaultFooter.name)

  const compactFooter = await prisma.receiptFooterTemplate.create({
    data: COMPACT_FOOTER,
  })
  console.log("  Created:", compactFooter.name)
  console.log("")

  // --- 4. Create receipt templates for all Ledger types (Ledger, Agent Receipt, Expenses Note, Debit Note) × both variants ---
  const receiptTypes: { type: string; label: string }[] = [
    { type: "ledger", label: "Ledger" },
    { type: "agent_receipt", label: "Agent Receipt" },
    { type: "expenses_note", label: "Expenses Note" },
    { type: "debit_note", label: "Debit Note" },
  ]

  console.log("Creating receipt templates (all types × slip + custom size)...")
  for (const { type, label } of receiptTypes) {
    for (const variant of ["slip_printer", "custom_size"] as const) {
      const name =
        variant === "slip_printer"
          ? `${label} – Slip printer`
          : `${label} – Custom size`
      await prisma.receiptTemplate.create({
        data: {
          name,
          type,
          variant,
          headerTemplateId: defaultHeader.id,
          footerTemplateId: defaultFooter.id,
          bodyContent: LEDGER_BODY,
          paperWidthMm: variant === "slip_printer" ? 80 : 210,
          paperHeightMm: variant === "slip_printer" ? null : 297,
          status: 1,
        },
      })
      console.log("  Created:", name, `(${type} / ${variant})`)
    }
  }

  console.log("\nDone.")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
