'use client';

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Selector } from '@/components/common/selector';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useToast } from '@/components/hooks/use-toast';
import { Download, FileSpreadsheet, FileText, Loader2, Printer, SearchIcon } from 'lucide-react';
import { getAgentBalanceReportData } from '@/app/actions/reports/agent-balance.report.action';
import type { AgentBalanceReportContentProps, AgentBalanceReportRow } from '@/types/reports/agent-balance';
import { formatLKR } from '@/lib/format-money';
import { formatExportFileName } from '@/lib/utils';
import { ReportAgentSelect } from '@/components/common/agent-select';
import { ReportGenerationDetailsCard } from '@/components/common/report-generation-details';
import {
  ReportPrintLayout,
  toBrandedPdfSummaryItems,
} from '@/components/common/report-print';
import type { ReportPrintSummaryItem } from '@/components/common/report-print';
import { ReportEmptyStateCard } from '@/components/common/report-empty-state';
import { AgentBalancePrintLayout } from './agent-balance-print-layout';
import { downloadAgentBalanceReportPdf } from './agent-balance-pdf';
import { downloadAgentBalanceReportExcel } from './agent-balance-excel';

const STATUS_OPTIONS = [
  { id: '1', name: 'Active' },
  { id: '0', name: 'Inactive' },
];

export default function AgentBalanceReportContent({ agentOptions, currentUserName }: AgentBalanceReportContentProps) {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [loadingExcel, setLoadingExcel] = useState(false);
  const [agentId, setAgentId] = useState('__all__');
  const [status, setStatus] = useState('__all__');
  const [rows, setRows] = useState<AgentBalanceReportRow[]>([]);
  const [reportMeta, setReportMeta] = useState<{
    agentLabel: string;
    statusLabel: string;
    generatedBy: string;
    generatedAt: string;
  } | null>(null);

  const balanceTotal = rows.reduce((sum, r) => sum + (Number(r.agentBalance) || 0), 0);

  const buildSummaryItems = (meta: {
    agentLabel: string;
    statusLabel: string;
    generatedBy: string;
    generatedAt: string;
  }): ReportPrintSummaryItem[] => [
    { label: 'Agent', value: meta.agentLabel },
    { label: 'Status', value: meta.statusLabel },
    { label: 'Generated By', value: meta.generatedBy },
    { label: 'Generated At', value: meta.generatedAt },
  ];

  const runSearch = async () => {
    setLoading(true);
    try {
      const res = await getAgentBalanceReportData({ agentId, status });
      if (!res.success) {
        toast({ variant: 'destructive', title: 'Error', description: res.message || 'Failed to load report' });
        setRows([]);
        setReportMeta(null);
        return;
      }
      const data = res.data ?? [];
      setRows(data);
      setReportMeta({
        agentLabel: agentOptions.find((a) => a.id === agentId)?.name ?? 'All Agents',
        statusLabel: STATUS_OPTIONS.find((s) => s.id === status)?.name ?? 'All Status',
        generatedBy: currentUserName,
        generatedAt: new Date().toLocaleString(),
      });
    } catch (error: unknown) {
      const msg = error instanceof Error ? error.message : 'Failed to load report';
      toast({ variant: 'destructive', title: 'Error', description: msg });
    } finally {
      setLoading(false);
    }
  };

  const renderMetaCard = () =>
    reportMeta ? (
      <ReportGenerationDetailsCard
        items={[
          {
            label: 'Filters',
            value: (
              <>
                Agent: {reportMeta.agentLabel} | Status: {reportMeta.statusLabel}
              </>
            ),
            smColSpan: 2,
          },
          { label: 'Generated by', value: <span className="font-semibold">{reportMeta.generatedBy}</span> },
          { label: 'Generated at', value: <span className="font-semibold">{reportMeta.generatedAt}</span> },
        ]}
      />
    ) : null;

  const downloadCsv = () => {
    if (rows.length === 0) {
      toast({ variant: 'destructive', title: 'No data', description: 'Run a search first to download.' });
      return;
    }
    const lines = [
      [
        'S No.',
        'Status',
        'Agent Code',
        'Parent Agent',
        'Agent Name',
        'Agent Phone No',
        'Agent Address',
        'Hard credit limit',
        'Agency credit limit',
        'Allowed credit limit',
        'Agent Balance',
      ].join(','),
      ...rows.map((r, i) =>
        [
          i + 1,
          r.status === 1 ? 'Active' : 'Inactive',
          r.agentCode,
          r.parentAgent,
          r.agentName,
          r.agentPhoneNo,
          r.agentAddress,
          r.hardCreditLimit.toFixed(2),
          r.agencyCreditLimit.toFixed(2),
          r.allowedCreditLimit.toFixed(2),
          r.agentBalance.toFixed(2),
        ]
          .map((v) => `"${String(v).replace(/"/g, '""')}"`)
          .join(',')
      ),
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `agent-balance-report-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadPdf = async () => {
    if (rows.length === 0) {
      toast({ variant: 'destructive', title: 'No data', description: 'Run a search first to download PDF.' });
      return;
    }
    if (!reportMeta) {
      toast({ variant: 'destructive', title: 'No data', description: 'Run a search first to download PDF.' });
      return;
    }
    await downloadAgentBalanceReportPdf({
      reportName: 'Agent Balance Report',
      summaryItems: toBrandedPdfSummaryItems(buildSummaryItems(reportMeta)),
      generatedAt: reportMeta.generatedAt,
      rows,
      balanceTotal,
      fileName: `${formatExportFileName('agent-balance-report')}.pdf`,
    });
  };

  const downloadExcel = async () => {
    if (rows.length === 0 || !reportMeta) {
      toast({ variant: 'destructive', title: 'No data', description: 'Run a search first to download Excel.' });
      return;
    }
    setLoadingExcel(true);
    try {
      await downloadAgentBalanceReportExcel({
        reportName: 'Agent Balance Report',
        summaryItems: toBrandedPdfSummaryItems(buildSummaryItems(reportMeta)),
        generatedAt: reportMeta.generatedAt,
        rows,
        balanceTotal,
        fileName: `${formatExportFileName('agent-balance-report')}.xlsx`,
        sheetName: 'Agent Balance',
      });
    } catch (error: unknown) {
      toast({
        variant: 'destructive',
        title: 'Excel export failed',
        description: error instanceof Error ? error.message : 'Unable to generate Excel.',
      });
    } finally {
      setLoadingExcel(false);
    }
  };

  return (
    <div className="w-full py-2 space-y-3 agent-balance-report-root">
      <Card className="print:hidden">
        <CardHeader className="pb-2">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
            <div>
              <CardTitle className="text-xl font-bold">Agent Balance Report</CardTitle>
              <CardDescription className="text-xs mt-0.5">
                Agent balances from agencies and linked PAYABLE accounts.
              </CardDescription>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={() => window.print()} className="gap-2"><Printer />Print</Button>
              <Button variant="outline" size="sm" onClick={downloadPdf} className="gap-2"><FileText />PDF</Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => {
                  void downloadExcel();
                }}
                disabled={loadingExcel}
                className="gap-2"
              >
                {loadingExcel ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <FileSpreadsheet className="h-4 w-4" />
                )}
                Excel
              </Button>
              <Button variant="outline" size="sm" onClick={downloadCsv} className="gap-2"><Download />Download CSV</Button>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-wrap items-end gap-4">
            <ReportAgentSelect
              label="Select Agent"
              agentOptions={agentOptions}
              value={agentId}
              onChange={(v) => setAgentId(v ?? '__all__')}
            />
            <Selector
              label="All Status"
              options={STATUS_OPTIONS}
              value={status}
              onChange={setStatus}
              className={{ trigger: 'w-[180px]' }}
            />
            <Button size="sm" onClick={runSearch} disabled={loading} className="h-10 gap-2">
              <SearchIcon className="h-4 w-4" />Search
            </Button>
          </div>
        </CardContent>
      </Card>

      {!reportMeta && (
        <div className="print:hidden">
          <ReportEmptyStateCard
            title="Run a search to view results"
            description="Select filters and click Search."
          />
        </div>
      )}

      {reportMeta && (
        <Card className="bg-muted/20 print:shadow-none print:border-0 print:bg-white">
          <CardHeader className="py-2 print:hidden">
            <CardTitle className="text-base">Agent Balance Report</CardTitle>
            <CardDescription className="text-xs mt-0.5">Agency soft/hard limits with live account balance.</CardDescription>
            {renderMetaCard()}
          </CardHeader>
          <CardContent className="space-y-3 py-2">
            <ReportPrintLayout
              reportName="Agent Balance Report"
              pageSize="A4 portrait"
              generatedAt={reportMeta.generatedAt}
              summaryItems={buildSummaryItems(reportMeta)}
            >
              {loading ? (
                <div className="text-center py-8">Loading...</div>
              ) : rows.length === 0 ? (
                <div className="print:hidden">
                  <ReportEmptyStateCard
                    title="No results"
                    description="No agents found for the selected filters."
                  />
                </div>
              ) : (
                <>
                  <div className="rounded-md border overflow-x-auto ab-screen-table print:hidden">
                    <Table className="text-[11px] [&_th]:px-1.5 [&_td]:px-1.5 [&_th]:border-r [&_th:last-child]:border-r-0 [&_td]:border-r [&_td:last-child]:border-r-0">
                      <TableHeader>
                        <TableRow className="border-b">
                          <TableHead className="w-10 text-right">No.</TableHead>
                          <TableHead>Status</TableHead>
                          <TableHead className="text-center">Agent Code</TableHead>
                          <TableHead>Parent Agent</TableHead>
                          <TableHead>Agent Name</TableHead>
                          <TableHead>Agent Phone No</TableHead>
                          <TableHead>Agent Address</TableHead>
                          <TableHead className="text-right">Hard credit limit</TableHead>
                          <TableHead className="text-right">Agency credit limit</TableHead>
                          <TableHead className="text-right">Allowed credit limit</TableHead>
                          <TableHead className="text-right">Agent Balance</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {rows.map((r, i) => (
                          <TableRow key={r.id} className="border-b border-border/50">
                            <TableCell className="text-center tabular-nums">{i + 1}</TableCell>
                            <TableCell>
                              <span
                                className={
                                  r.status === 1
                                    ? 'inline-flex items-center rounded px-2 py-0.5 text-[10px] font-medium bg-emerald-50 text-emerald-700'
                                    : 'inline-flex items-center rounded px-2 py-0.5 text-[10px] font-medium bg-red-100/70 text-red-700'
                                }
                              >
                                {r.status === 1 ? 'Active' : 'Inactive'}
                              </span>
                            </TableCell>
                            <TableCell className="text-center">{r.agentCode}</TableCell>
                            <TableCell>{r.parentAgent}</TableCell>
                            <TableCell>{r.agentName}</TableCell>
                            <TableCell>{r.agentPhoneNo}</TableCell>
                            <TableCell>{r.agentAddress}</TableCell>
                            <TableCell className="text-right tabular-nums">{formatLKR(r.hardCreditLimit)}</TableCell>
                            <TableCell className="text-right tabular-nums">{formatLKR(r.agencyCreditLimit)}</TableCell>
                            <TableCell className="text-right tabular-nums">{formatLKR(r.allowedCreditLimit)}</TableCell>
                            <TableCell className="text-right tabular-nums">{formatLKR(r.agentBalance)}</TableCell>
                          </TableRow>
                        ))}
                        <TableRow className="rpt-print-total font-medium bg-muted/50">
                          <TableCell colSpan={10}>Total</TableCell>
                          <TableCell className="text-right tabular-nums">{formatLKR(balanceTotal)}</TableCell>
                        </TableRow>
                      </TableBody>
                    </Table>
                  </div>
                  <div className="ab-print-only hidden print:block">
                    <AgentBalancePrintLayout rows={rows} balanceTotal={balanceTotal} />
                  </div>
                  <div className="print:hidden">{renderMetaCard()}</div>
                </>
              )}
            </ReportPrintLayout>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
