/**
 * Hardcoded list of tracked activity actions from ACTIVITY_LOG_AUDIT.md.
 * Used for the "View all tracked actions" reference in the User Activity report.
 */
export const ACTIVITY_ACTIONS_AUDIT: Array<{ action: string; importance: string; when: string }> = [
  { action: 'till.visited', importance: 'Low', when: 'User opens My Till page' },
  { action: 'till.statement.viewed', importance: 'Low', when: 'User fetches till statement (with optional date range)' },
  { action: 'ledger.visited', importance: 'Low', when: 'User opens Ledger page' },
  { action: 'ledger.receipt.created', importance: 'High', when: 'User creates a ledger transaction (receipt)' },
  { action: 'accounting.visited', importance: 'Low', when: 'User opens Accounting (chart of accounts) page' },
  { action: 'accounting.statement.viewed', importance: 'Low', when: 'User views an account statement' },
  { action: 'accounting.account.created', importance: 'High', when: 'User creates an account' },
  { action: 'accounting.account.updated', importance: 'High', when: 'User updates an account' },
  { action: 'channel-booking.visited', importance: 'Low', when: 'User opens Channel Booking page' },
  { action: 'channel-booking.booking.created', importance: 'High', when: 'User creates a booking' },
  { action: 'booking.transferred', importance: 'High', when: 'Bookings are transferred (e.g. session/doctor change)' },
  { action: 'booking.updated', importance: 'High', when: 'Booking details are updated from the Change tab (stores before/after patient fields)' },
  { action: 'sessions.visited', importance: 'Low', when: 'User opens Sessions page' },
  { action: 'session.created.bulk', importance: 'High', when: 'Sessions created (e.g. bulk creation)' },
  { action: 'session.updated', importance: 'High', when: 'Session updated' },
  { action: 'session.deleted', importance: 'High', when: 'Session deleted' },
  { action: 'session.sms_sent', importance: 'High', when: 'SMS sent to session (e.g. reminder)' },
  { action: 'doctors.visited', importance: 'Low', when: 'User opens Doctors page' },
  { action: 'doctors.doctor.created', importance: 'High', when: 'User creates a doctor' },
  { action: 'doctors.doctor.updated', importance: 'High', when: 'User updates a doctor' },
  { action: 'doctors.doctor.deleted', importance: 'High', when: 'User deletes a doctor' },
  { action: 'doctors.doctors.bulkDeleted', importance: 'High', when: 'User bulk-deletes doctors' },
  { action: 'doctors.exported', importance: 'Medium', when: 'User exports doctors list' },
  { action: 'doctor-sessions.visited', importance: 'Low', when: 'User opens Doctor Sessions page' },
  { action: 'doctor-sessions.session.created', importance: 'High', when: 'User creates a doctor session' },
  { action: 'doctor-sessions.session.updated', importance: 'High', when: 'User updates a doctor session' },
  { action: 'doctor-sessions.session.deleted', importance: 'High', when: 'User deletes a doctor session' },
  { action: 'doctor-sessions.sessions.bulkDeleted', importance: 'High', when: 'User bulk-deletes doctor sessions' },
  { action: 'specialities.visited', importance: 'Low', when: 'User opens Specialities page' },
  { action: 'specialities.speciality.created', importance: 'High', when: 'User creates a speciality' },
  { action: 'specialities.speciality.updated', importance: 'High', when: 'User updates a speciality' },
  { action: 'specialities.speciality.deleted', importance: 'High', when: 'User deletes a speciality' },
  { action: 'specialities.specialities.bulkDeleted', importance: 'High', when: 'User bulk-deletes specialities' },
  { action: 'specialities.exported', importance: 'Medium', when: 'User exports specialities list' },
  { action: 'doctor-leaves.visited', importance: 'Low', when: 'User opens Doctor Leaves page' },
  { action: 'doctor-leaves.leave.created', importance: 'High', when: 'User creates a doctor leave' },
  { action: 'doctor-leaves.leave.updated', importance: 'High', when: 'User updates a doctor leave' },
  { action: 'doctor-leaves.leave.deleted', importance: 'High', when: 'User deletes a doctor leave' },
  { action: 'doctor-leaves.leaves.bulkDeleted', importance: 'High', when: 'User bulk-deletes doctor leaves' },
  { action: 'departments.visited', importance: 'Low', when: 'User opens Departments page' },
  { action: 'departments.department.created', importance: 'High', when: 'User creates a department' },
  { action: 'departments.department.updated', importance: 'High', when: 'User updates a department' },
  { action: 'departments.department.deleted', importance: 'High', when: 'User deletes a department' },
  { action: 'departments.departments.bulkDeleted', importance: 'High', when: 'User bulk-deletes departments' },
  { action: 'departments.exported', importance: 'Medium', when: 'User exports departments list' },
  { action: 'zones.visited', importance: 'Low', when: 'User opens Zones page' },
  { action: 'zones.zone.created', importance: 'High', when: 'User creates a zone' },
  { action: 'zones.zone.updated', importance: 'High', when: 'User updates a zone' },
  { action: 'zones.zone.deleted', importance: 'High', when: 'User deletes a zone' },
  { action: 'zones.zones.bulkDeleted', importance: 'High', when: 'User bulk-deletes zones' },
  { action: 'zones.exported', importance: 'Medium', when: 'User exports zones list' },
  { action: 'rooms.visited', importance: 'Low', when: 'User opens Rooms page' },
  { action: 'rooms.room.created', importance: 'High', when: 'User creates a room' },
  { action: 'rooms.room.updated', importance: 'High', when: 'User updates a room' },
  { action: 'rooms.room.deleted', importance: 'High', when: 'User deletes a room' },
  { action: 'rooms.rooms.bulkDeleted', importance: 'High', when: 'User bulk-deletes rooms' },
  { action: 'rooms.exported', importance: 'Medium', when: 'User exports rooms list' },
  { action: 'locations.visited', importance: 'Low', when: 'User opens Locations page' },
  { action: 'locations.location.created', importance: 'High', when: 'User creates a location' },
  { action: 'locations.location.updated', importance: 'High', when: 'User updates a location' },
  { action: 'locations.location.deleted', importance: 'High', when: 'User deletes a location' },
  { action: 'locations.locations.bulkDeleted', importance: 'High', when: 'User bulk-deletes locations' },
  { action: 'locations.exported', importance: 'Medium', when: 'User exports locations list' },
  { action: 'patients.visited', importance: 'Low', when: 'User opens Patients page' },
  { action: 'patients.patient.created', importance: 'High', when: 'User creates a patient' },
  { action: 'patients.patient.updated', importance: 'High', when: 'User updates a patient' },
  { action: 'patients.patient.deleted', importance: 'High', when: 'User deletes a patient' },
  { action: 'patients.patients.bulkDeleted', importance: 'High', when: 'User bulk-deletes patients' },
  { action: 'patients.exported', importance: 'Medium', when: 'User exports patients list' },
  { action: 'staff.visited', importance: 'Low', when: 'User opens Staff page' },
  { action: 'staff.staff.created', importance: 'High', when: 'User creates a staff member' },
  { action: 'staff.staff.updated', importance: 'High', when: 'User updates a staff member' },
  { action: 'staff.staff.deleted', importance: 'High', when: 'User deletes a staff member' },
  { action: 'staff.staff.bulkDeleted', importance: 'High', when: 'User bulk-deletes staff' },
  { action: 'staff.exported', importance: 'Medium', when: 'User exports staff list' },
  { action: 'users.visited', importance: 'Low', when: 'User opens Users page' },
  { action: 'users.user.created', importance: 'High', when: 'User creates a user' },
  { action: 'users.user.updated', importance: 'High', when: 'User updates a user' },
  { action: 'users.user.deleted', importance: 'High', when: 'User deletes a user' },
  { action: 'users.users.bulkDeleted', importance: 'High', when: 'User bulk-deletes users' },
  { action: 'users.exported', importance: 'Medium', when: 'User exports users list' },
  { action: 'user-groups.visited', importance: 'Low', when: 'User opens User Groups page' },
  { action: 'user-groups.userGroup.created', importance: 'High', when: 'User creates a user group' },
  { action: 'user-groups.userGroup.updated', importance: 'High', when: 'User updates a user group' },
  { action: 'agency-books.visited', importance: 'Low', when: 'User opens Agency Books page' },
  { action: 'agency-books.agencyBook.created', importance: 'High', when: 'User creates an agency book' },
  { action: 'agency-books.agencyBook.updated', importance: 'High', when: 'User updates an agency book' },
  { action: 'agency-books.agencyBook.deleted', importance: 'High', when: 'User deletes an agency book' },
  { action: 'agency-books.agencyBooks.bulkDeleted', importance: 'High', when: 'User bulk-deletes agency books' },
  { action: 'agency-books.exported', importance: 'Medium', when: 'User exports agency books list' },
  { action: 'agencies.visited', importance: 'Low', when: 'User opens Agencies page' },
  { action: 'agencies.agency.created', importance: 'High', when: 'User creates an agency' },
  { action: 'agencies.agency.updated', importance: 'High', when: 'User updates an agency' },
  { action: 'agencies.agency.deleted', importance: 'High', when: 'User deletes an agency' },
  { action: 'agencies.agencies.bulkDeleted', importance: 'High', when: 'User bulk-deletes agencies' },
  { action: 'agencies.exported', importance: 'Medium', when: 'User exports agencies list' },
  { action: 'agencies.credit_violation_cleared_manually', importance: 'High', when: 'User clears agency credit violation from list when balance is eligible' },
  { action: 'credit-customers.visited', importance: 'Low', when: 'User opens Credit Customers page' },
  { action: 'credit-customers.creditCustomer.created', importance: 'High', when: 'User creates a credit customer' },
  { action: 'credit-customers.creditCustomer.updated', importance: 'High', when: 'User updates a credit customer' },
  { action: 'credit-customers.creditCustomer.deleted', importance: 'High', when: 'User deletes a credit customer' },
  { action: 'credit-customers.creditCustomers.bulkDeleted', importance: 'High', when: 'User bulk-deletes credit customers' },
  { action: 'credit-customers.exported', importance: 'Medium', when: 'User exports credit customers list' },
  { action: 'discounts.visited', importance: 'Low', when: 'User opens Discounts page' },
  { action: 'discounts.discount.created', importance: 'High', when: 'User creates a discount' },
  { action: 'discounts.discount.updated', importance: 'High', when: 'User updates a discount' },
  { action: 'discounts.discount.deleted', importance: 'High', when: 'User deletes a discount' },
  { action: 'discounts.discounts.bulkDeleted', importance: 'High', when: 'User bulk-deletes discounts' },
  { action: 'discounts.exported', importance: 'Medium', when: 'User exports discounts list' },
  { action: 'bulk-cashier.visited', importance: 'Low', when: 'User opens Bulk Cashier page' },
  { action: 'float-transfers.visited', importance: 'Low', when: 'User opens Float Transfers page' },
  { action: 'float-transfers.floatRequest.approved', importance: 'High', when: 'Bulk cashier approves a float request' },
  { action: 'shifts.visited', importance: 'Low', when: 'User opens Shifts page' },
  { action: 'shift.started', importance: 'High', when: 'User starts a shift' },
  { action: 'shift.paused', importance: 'High', when: 'User pauses a shift' },
  { action: 'shift.resumed', importance: 'High', when: 'User resumes a shift' },
  { action: 'shift.ended', importance: 'High', when: 'User ends a shift' },
  { action: 'tags.visited', importance: 'Low', when: 'User opens Tags page' },
  { action: 'tags.tag.created', importance: 'High', when: 'User creates a tag' },
  { action: 'tags.tag.updated', importance: 'High', when: 'User updates a tag' },
  { action: 'tags.tag.deleted', importance: 'High', when: 'User deletes a tag' },
  { action: 'tags.tags.bulkDeleted', importance: 'High', when: 'User bulk-deletes tags' },
  { action: 'tags.exported', importance: 'Medium', when: 'User exports tags list' },
  { action: 'sms-playground.visited', importance: 'Low', when: 'User opens SMS Playground page' },
  { action: 'sms-templates.visited', importance: 'Low', when: 'User opens SMS Templates page' },
  { action: 'sms-templates.template.created', importance: 'High', when: 'User creates an SMS template' },
  { action: 'sms-templates.template.updated', importance: 'High', when: 'User updates an SMS template' },
  { action: 'sms-templates.template.deleted', importance: 'High', when: 'User deletes an SMS template' },
  { action: 'sms-templates.templates.bulkDeleted', importance: 'High', when: 'User bulk-deletes SMS templates' },
  { action: 'reports.visited', importance: 'Low', when: 'User opens Reports (index) page' },
  { action: 'reports.agent-detail.exported', importance: 'Medium', when: 'User exports Agent Detail report' },
  { action: 'reports.doctors.exported', importance: 'Medium', when: 'User exports Doctors report' },
  { action: 'reports.channel-agent-reference-book.exported', importance: 'Medium', when: 'User exports Channel Agent Reference Book report' },
  { action: 'reports.doctor-arrivals.exported', importance: 'Medium', when: 'User exports Doctor Arrivals report' },
  { action: 'reports.user-activity.exported', importance: 'Medium', when: 'User exports User Activity report (capped at 10k; note if more exist)' },
  { action: 'admin.receipt-templates.visited', importance: 'Low', when: 'User opens Receipt templates page' },
  { action: 'shift.handover.sent_to_reconciliation', importance: 'High', when: 'Bulk cashier sends approved handover to a specific reconciler' },
  { action: 'shift.handover.reconciliation_assignee_changed', importance: 'High', when: 'Reconciler assignment is changed before completion' },
  { action: 'shift.handover.reconciliation_submitted', importance: 'High', when: 'Assigned reconciler submits reconciliation' },
  { action: 'shift.handover.reconciliation_rejected', importance: 'High', when: 'Assigned reconciler rejects reconciliation' },
  { action: 'admin.receipt-templates.template.created', importance: 'High', when: 'User creates a receipt template' },
  { action: 'admin.receipt-templates.template.updated', importance: 'High', when: 'User updates a receipt template' },
  { action: 'admin.receipt-templates.template.deleted', importance: 'High', when: 'User deletes a receipt template' },
  { action: 'admin.receipt-templates.header.deleted', importance: 'High', when: 'User deletes a receipt header template' },
  { action: 'admin.receipt-templates.footer.deleted', importance: 'High', when: 'User deletes a receipt footer template' },
  { action: 'admin.api-clients.visited', importance: 'Low', when: 'User opens API Clients page' },
  { action: 'admin.api-clients.client.created', importance: 'High', when: 'User creates an API client' },
  { action: 'admin.api-clients.client.updated', importance: 'High', when: 'User updates an API client' },
];
