import type { DoctorSession } from '@/types/doctor.session';

export type ChannelScheduleWithChargesReportQuery = {
  institutionId?: string;
  locationId?: string;
  departmentId?: string;
  specialityId?: string;
  doctorId?: string;
  /**
   * '__all__' / undefined => both specific-date and weekday sessions
   * 'specific_date' => dayType 8
   * 'weekday' => dayType 1–7
   */
  reportType?: string;
};

export type ChannelScheduleWithChargesReportRow = Pick<
  DoctorSession,
  | 'id'
  | 'name'
  | 'institution'
  | 'startTime'
  | 'endTime'
  | 'startingPatientNumber'
  | 'maxPatientNumber'
  | 'refundable'
  | 'advancedBookingEnabled'
  | 'fees'
  | 'amountLocal'
  | 'amountForeign'
  | 'applyTo'
  | 'dayType'
  | 'status'
> & {
  doctor?: {
    id?: string;
    name?: string;
    code?: string;
    title?: string;
  } | null;
  location?: {
    id?: string;
    name?: string;
  } | null;
  room?: {
    id?: string;
    number?: string;
    description?: string;
  } | null;
  department?: {
    id?: string;
    name?: string;
  } | null;
  previousSession?: {
    id?: string;
    name?: string;
  } | null;
};

export type ChannelScheduleWithChargesReportExportRow = {
  locationName: string;
  doctorName: string;
  sessionName: string;
  roomName: string;
  startTime: string;
  endTime: string;
  dateType: string;
  applyOnlyTo: string;

  doctorFeeLocal: number | null;
  hospitalFeeLocal: number | null;
  agencyFeeLocal: number | null;
  scanFeeLocal: number | null;
  onCallFeeLocal: number | null;
  creditCardCommissionLocal: number | null;
  apiFeeLocal: number | null;
  sessionValueLocal: number | null;

  doctorFeeForeign: number | null;
  hospitalFeeForeign: number | null;
  agencyFeeForeign: number | null;
  scanFeeForeign: number | null;
  onCallFeeForeign: number | null;
  creditCardCommissionForeign: number | null;
  apiFeeForeign: number | null;
  sessionValueForeign: number | null;

  startingPatientNo: number | string;
  maximumPatientNo: number | string;
  previousSession: string;

  refundable: string;
  advanceBookingEnabled: string;
  status: string;
};

export type ChannelScheduleWithChargesReportContentProps = {
  /** Display name for "Generated by" in report generation details. */
  currentUserName: string;
  institutionOptions: Array<{ id: string; name: string }>;
  locationOptions: Array<{ id: string; name: string }>;
  departmentOptions: Array<{ id: string; name: string }>;
  specialityOptions: Array<{ id: string; name: string }>;
  doctorOptions: Array<{ id: string; name: string }>;
};

