/**
 * Accounting service – barrel re-export.
 * Implementation lives in services/accounting/ (account, balance-calc, balance, journal, statement).
 */
export {
  getAccountBalance,
  getAccountBalanceWithTx,
  type AccountingTx,
  getMainCashBookAccount,
  getCashBookAccountForBranch,
  getCashAccountByUserId,
  getOrCreateAccount,
  getOrCreateWhtPayableAccount,
  WHT_PAYABLE_ACCOUNT_CODE,
  WHT_PAYABLE_NAME,
  createAccount,
  updateAccount,
  getAccountById,
  getAllAccounts,
  getLinkedAccountUserOptions,
  type GetOrCreateAccountParams,
  type GetAllAccountsParams,
  getBranchCashBalance,
  getCashierFloatBalance,
  getFullInstituteCashBalance,
  getTillBalanceBreakdown,
  getTillBalanceBreakdownForAccount,
  getTillBalanceCentsByMethod,
  ensureTillForUserLocation,
  resolveActiveTillForUserLocation,
  resolveTillForUserAndLocation,
  listTillsForUser,
  type ResolvedTill,
  type TillBalanceBreakdown,
  createJournalEntry,
  createJournalEntryInTransaction,
  checkJournalEntryBalance,
  getAccountStatement,
} from './accounting';
